### ISSUE TITLE
Reset without knowing hash

### ISSUE THREAD

**Issue by Mopster** [APY/APYDataGridBundle#1007]
I'm currently struggling with finding a way to reset any existing filters in the session of a grid.

Let's say we go to the grid and filter on column A and B. We go to another page which contains a link to the same grid with a URL parameter designating the grid should filter on column C. We currently use the 'default filters' to add a filter on column C. But the problem is the session still contains a filter on column A and B and there's no way to reset these without knowing the hash. All relevant methods related to the hash, session or filters are protected, and all available options require the hash.

We can't use the  `?grid_myGridID[_reset]` since we don't have the grid hash before calling `getGridResponse`.

**Comment by DonCallisto** [comment]
You can assing an `id` to the grid and request a reset for it.

**Comment by Mopster** [comment]
I tried that, but it still adds the hash behind the id : grid_gridID_hash

**Comment by DonCallisto** [comment]
Just compose a link with

`'grid_' . $grid->getId() . '[_reset]`

**Comment by Mopster** [comment]
Tried just that, doesn't work
```
$this->createHash();

        $this->requestData = (array) $this->request->get($this->hash);

        $this->processPersistence();

        $this->sessionData = (array) $this->session->get($this->hash);
```

```
// Persistence or reset - kill previous session
        if ((!$this->request->isXmlHttpRequest() && !$this->persistence && $referer != $this->getCurrentUri())
         || isset($this->requestData[self::REQUEST_QUERY_RESET])) {
            $this->session->remove($this->hash);
        }
```
Hash is added to the ID in Grid.php to get data from the request
```
protected function createHash()
    {
        //$this->hash = 'grid_'. (empty($this->id) ? md5($this->request->get('_controller').$this->columns->getHash().$this->source->getHash()) : $this->getId());
        $hash = md5($this->request->get('_controller').$this->columns->getHash().$this->source->getHash());
        if ($id = $this->getId()) {
            $hash = $id . '_' . $hash;
        }
        $this->hash = 'grid_' . $hash;
    }
```

**Comment by DonCallisto** [comment]
I'm using this method in every project of mine where this bundle is a dependency at it just works.
As I told you, you need to set an id to the Grid when you create it

**Comment by Mopster** [comment]
@DonCallisto alright, I figured it out, looks like I was dealing with some very old hacks in our code. Thanks for your help.
