### ISSUE TITLE
Compatibility with symfony flex

### ISSUE THREAD

**Issue by nicodmf** [APY/APYDataGridBundle#1008]
As Symfony flex doesnt install all symfony/symfony package, this is not installable. It would be better to fix dependency more precis.

**Comment by DonCallisto** [comment]
Symfony flex has nothing to do with this but I agree we should ask only for certain specific dependencies as symfony 4 tendency is to split components required as much as possible.
However you dind't required all the minimum symfony deps (look at failed test).
You should search for `Symfony` namespace and require *all* this project needs.

**Comment by DonCallisto** [comment]
Let's close this and continue the discussion in #1009
