### ISSUE TITLE
Implement compatibility with symfony flex

### ISSUE THREAD

**Issue by Scuottolinx** [APY/APYDataGridBundle#1020]
This package requires the "symfony / symfony" package, but in symfony flex it is set up as a conflict.

**Comment by DonCallisto** [comment]
[Master branch](https://github.com/APY/APYDataGridBundle/blob/master/composer.json) is not. Still waiting [for @romainguerrero feedback](https://github.com/APY/APYDataGridBundle/pull/1011) before drafting a new release.
Please follow linked discussion.
