### ISSUE TITLE
"_self template“ doesn't work.

### ISSUE THREAD

**Issue by slince** [APY/APYDataGridBundle#1022]
This is my template:

```jinja
{% extends 'AcmeBundle::layout.html.twig' %}

{% block pageHeader %}
<h1>
    {{ 'admin.user.management'|trans }}
    <small>{{ 'admin.user.index'|trans }}</small>
</h1>
{% endblock %}

{% block content %}
    {{ grid(grid, _self) }}
{% endblock %}

{% block grid_filters %}
{% endblock %}
```

error:

 ```
An exception has been thrown during the rendering of a template ("Block "grid" doesn't exist in grid template "AcmeBundle:User:index.html.twig".").
```

it does not work like the follow:

> If you want to override blocks inside the current template you can use the _self parameter in grid template definition. Current template will automatically extended from the base block template (APYDataGridBundle::blocks.html.twig)

Looking forward to your reply.

**Comment by DonCallisto** [comment]
Well, what is `'AcmeBundle::layout.html.twig`? Maybe you're not extending the right templates?

**Comment by slince** [comment]
`AcmeBundle::layout.html.twig` is a basic layout template.  like 

```html

<html>
<head>admin</head>
<body>
<div class="content-wrapper">
        <section class="content-header">
            {% block pageHeader %}{% endblock %}
            {{ breadcrumb(admin_breadcrumb)|raw }}
        </section>
        <section class="content">
        {% block content %}{% endblock %}
        </section>
    </div>
</body>
```

**Comment by DonCallisto** [comment]
Is the first template overriding the bundle one? Could you tell me the name of this template and the path? Thanks.

**Comment by slince** [comment]
> Is the first template overriding the bundle one
No

this is my controller code.
```
    /**
     * 用户管理列表
     *
     * @Route("/users", name="admin_user_index")
     */
    public function indexAction()
    {
        $this->breadcrumb->push('admin.user.index');
        $grid = $this->gridFactory->get(User::class);

        return $grid->getGridResponse('AcmeBundle:User:index.html.twig');
    }
```

**Comment by DonCallisto** [comment]
Ok, so if it is not overriding, how do you expect this to work? 
That's not an issue with the bundle but an issue with your code.

I'm closing this.

**Comment by slince** [comment]
hi, can you tell me how to do so it can work.

**Comment by DonCallisto** [comment]
Sorry, my fault, you don't need to extend or override anything. It seems like the `DataGridExtension` isn't registered. Weird.

**Comment by slince** [comment]
`DataGridExtension ` has been registered. it can work using  default theme.

```jinja
...
{{ grid(grid) }}
...
```

**Comment by slince** [comment]
![image](https://user-images.githubusercontent.com/3785826/44841338-b6a1ac80-ac75-11e8-8a8b-448b1a5ab4ee.png)

**Comment by DonCallisto** [comment]
So I think it's not an issue of this bundle

**Comment by slince** [comment]
ok, can you tell me some core code about "self template". so i can debug it by myself.

**Comment by DonCallisto** [comment]
You can view all the logic starting from `DataGridExtension`

**Comment by slince** [comment]
I think it's because beacause the `_self` variable return the current template name, not the template instance from [twig 2.0.0](https://github.com/twigphp/Twig/blob/1329b5580fad7a4fa9fe321973a9bb8d4631b4f3/CHANGELOG#L112)

**Comment by slince** [comment]
Hi,

I am a little confused. i don't know why [`getTemplatesFromString`](https://github.com/APY/APYDataGridBundle/blob/18356f17595dc4e09cb89a43b92220341215e182/Twig/DataGridExtension.php#L457) need to find parents of the template. 

i think it's not necessary, you know,
blocks in the parent template can be overwritten by the current template.

**Comment by DonCallisto** [comment]
Sorry, ATM I'm not able to take a look at this due to my little free time and due to the fact I'm the only devel that's following the project but I didn't wrote it.
If you want to submit a PR, you're welcome but I really don't know if and when I'll have the time to look and eventually merge it.

**Comment by slince** [comment]
Hi, i have expanded the class `DataGridExtension` and rewritten  method `getTemplates` like this:

```php
    protected function getTemplates(Twig_Environment $environment)
    {
        if ($this->templates) {
            return $this->templates;
        }
        $this->templates[] = $environment->load($this->defaultTemplate);
        if ($this->theme) {
            if (!$this->theme instanceof \Twig_Template && !$this->theme instanceof \Twig_TemplateWrapper) {
                $template = $environment->load($this->theme);
            } else {
                $template = $this->theme;
            }
            $this->templates[] = $template;
        }
        return $this->templates;
    }
```
and it works now for me.  if you think this is ok, i will submit a pr. 😃
