### ISSUE TITLE
You have requested a non-existent service "grid".

### ISSUE THREAD

**Issue by tzji7** [APY/APYDataGridBundle#1023]
![przechwycenie obrazu ekranu_2018-10-09_14-11-08](https://user-images.githubusercontent.com/43992138/46668616-34d66480-cbcd-11e8-94e6-940503171ff4.png)

**Comment by tzji7** [comment]
Syfony 3.4 and bundle latest.

pt., 12 paź 2018, 19:24 użytkownik Samuele Lilli <notifications@github.com>
napisał:

**Comment by DonCallisto** [comment]
I'm seeing we're not release any version with this fix. Please, try to use `dev-master` for this bundle. If this solve, tonight I'll release a bugfix version.

**Comment by tzji7** [comment]
Ok. thanks.

pt., 12 paź 2018 o 19:30 Samuele Lilli <notifications@github.com>
napisał(a):

**Comment by psssix** [comment]
Goodnight.
When I tried to require the "dev-service_autowire_definition" branch, on the symfony 4.3 , I received the following error:
![23859566524b7946a51b24dccf5079e3](https://user-images.githubusercontent.com/847629/51793411-53d72180-21d1-11e9-8e75-35f50c32de90.png)

**Comment by npotier** [comment]
Hello @tzji7 and @psssix the anwser can be found here : #1033 

I'm closing this issue.
