### ISSUE TITLE
Controller deprecated on Symfony 4

### ISSUE THREAD

**Issue by 6mon** [APY/APYDataGridBundle#1034]
Hello,

With Symfony 4, the bundle works only with the old `Symfony\Bundle\FrameworkBundle\Controller\Controller` class which is now deprecated. How can we use the new `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` ?
Is it possible to fix that ?

Thank you very much for this great bundle

**Comment by FlorianBourdoux** [comment]
Hello, 
I have the same problem.
I suppose we should override getSubscribedServices() of the AbstractController to be able to call the service, but I'm new on Symfony and I did not fund the solution to do it yet

**Comment by rvanlaarhoven** [comment]
You can just use the AbstractController, but you'll have to inject the grid service in your controller/action:

In services.yaml:

```yaml
APY\DataGridBundle\Grid\Grid: '@grid'
```

In your controller:

```php
use APY\DataGridBundle\Grid\Grid;

public function yourAction(Grid $grid)
{

}
```

**Comment by 6mon** [comment]
It's work, thanks ;-)
