### ISSUE TITLE
Symfony 6.0

### ISSUE THREAD

**Issue by kaamaa** [APY/APYDataGridBundle#1075]
Hi,
has anybody used the APYDataGridBundle with Symfony 6 yet?
Cheers
Martin

**Comment by chiragpurohit71085** [comment]
Hi 

I got a project to update to symfony to v6, but it seems this package is yet not compatible... any solution/workaround?

**Comment by FredDut** [comment]
Hi,
I've made some fixes and it seems to work with SF6. I don't know where to push (new PR?)

**Comment by npotier** [comment]
Hello @FredDut thank you !

You can start by creating a PR, it would be very nice.

**Comment by FredDut** [comment]
Hello,
I've made the pull request https://github.com/APY/APYDataGridBundle/pull/1087#issue-1877092079.
I'm wondering what and how to do with php attributes support.

**Comment by nacesprin** [comment]
Any update for this?

**Comment by npotier** [comment]
Indeed : https://github.com/APY/APYDataGridBundle/pull/1087
