### ISSUE TITLE
@TODO List

### ISSUE THREAD

**Issue by Abhoryo** [APY/APYDataGridBundle#121]
* <del>Date filter #41</del>
* <del>Export data #31</del> (v2)
* <del>New documentation structure + update</del> (v2)
* <del>Add dql function support on non-mapped fields</del>
* <del>Add number of results</del> and show the current range of result (v2)
* <del>Full php configuration #44</del> (v2)
* Yaml configuration #44 + #4
* <del>Xml configuration #44</del>
* <del>Implement all options on Document source #32 + others</del> (v2)
* Implement Propel source #86
* <del>Reset filters #36</del> (v2)
* <del>Custom/combo filter #28</del>
* <del>Prevent SQL injection ? #73</del>
* <del>New branch for Symfony 2.1</del> (v2) v2.0 works with Symfony 2.1.0 too
* <del>Lazy loading to add options in any order</del> (v2)
* <del>Manipulate the default action column</del> (v2)
* <del>Add role control on massAction, rowAction, Export</del> (v2.1)
* <del>Add sourceselect support for the vector source [#113]</del> (v2)
* <del>Add XMLHttpRequest full support [#130]</del>
* <del>searchOnClick feature</del> (v2.1)
* <del>Fix #201</del>
* Add footer aggregate informations (avg, count, ...) [#207]
* Add the number of results corresponding of a value in a select filter. (See the genre filter on http://dj.beatport.com/events)
* <del>[Filter] Add radio and checkbox filters.</del>
* <del>Add an attribute to turn off the escape of the value of a cell. [#257]</del>
* Merge rowAction and massAction [#22]
* Add cache support for result/page [#417]
* Add ajax refresh after row action (add a param)
* Add request parameters mapping (i.e. grid_id[_page] = $page) - Add a converter callback($name, $value) for encode parameter

**Comment by hmert** [comment]
I'll close this issue for new one.
