### ISSUE TITLE
In Grid how to display textbox for date type field

### ISSUE THREAD

**Issue by sanraj** [APY/APYDataGridBundle#140]
I used "S0RIEN / DataGridBundle" & for JQuery(jquery_date) "IoFormBundle" so in my grid textbox is not getting display.
for sorting/searching purpose.

Thanks.

**Comment by RodolVelasco** [comment]
How can I set date values by default? And how can I search date values with the filter (I have tried many formats but no one seems to work)?

**Comment by Abhoryo** [comment]
You have to set your langage in symfony, then the columns must be a date or datetime.
