### ISSUE TITLE
Date format in filter

### ISSUE THREAD

**Issue by olivier3400** [APY/APYDataGridBundle#143]
In a date column I set ( ... format="d/m/Y" ...) in the @GRID definition. Rendering is ok, but in the filter field it uses the US format "m/d/Y".

Does somebody know how to do to have the same format in cells and filters in a date column?

**Comment by anthonyherve** [comment]
Hello,

Have you fine a good solution to this problem ? I have same issue.

Thanks.

Anthony

**Comment by olivier3400** [comment]
Unfortunately not. I have explained to users to use only US dates for filtering

**Comment by anthonyherve** [comment]
In fact, I resolved my problem with this issue (https://github.com/Abhoryo/APYDataGridBundle/issues/468). Maybe you can be interested.
