### ISSUE TITLE
Totals Sum/avg/etc in footer and/or header

### ISSUE THREAD

**Issue by listeroabsoluto** [APY/APYDataGridBundle#207]
I dont know if this is a new feature or already exists, but would be great in the header or footer of the grid we can insert a row with totals / averages for each column.

Something like this:

    Customer     Invoice(count)    Ammount(sum)
    Jhon         2                 1000
    Mary         4                 1800
    -------------------------------------------
    Total        6                 2800

Thanks.

**Comment by Fuujin** [comment]
Hi,
is there any news about this feature?
Would be nice if I could use the functionality from the bundle instead of building my own.

**Comment by hmert** [comment]
https://github.com/APY/APYDataGridBundle/pull/552

**Comment by Fuujin** [comment]
Why was this issue closed? This issue is not the same as #552.
The issue is about  a summary row below the datagrid, not another column from the entity.

**Comment by hmert** [comment]
It's releated i thing. I'm trying to handle with 90 issue. We need to group some of them. At version 3. this will be implemented. If you have time, purpose a PR. We may include it to 2.3
