### ISSUE TITLE
Grid-Class should not be a Service

### ISSUE THREAD

**Issue by mkrauser** [APY/APYDataGridBundle#250]
In my Opinion, the Grid-Class should not be defined as a Service. 

There should be a service, to create grids (a GridFactory), just like this

```php
$grid = $this->get('grid_factory')->create($id);
```

The factory can inject the required services (request, session etc.) into each grid. That way, the actual Grid's don't need a reference to the Service-Container anymore, which means more testable code.

Also it would be easier to work with more than one grid, you just have a variable for each one.

**Comment by hmert** [comment]
@mkrauser ping! :) do you have few free hours for PR?

**Comment by mkrauser** [comment]
Sorry, we are not using this bundle anymore. So I won't be able to do a PR

**Comment by qferr** [comment]
@mkrauser I understand, for which reason I developped a feature (for 2.3) to make easier the grid constructor with builder and factory pattern. I was inspired by the Syfony Form component. A documentation is available [here](https://github.com/qferr/APYDataGridBundle/blob/2.3/Resources/doc/grid.md).
