### ISSUE TITLE
Problem with filter

### ISSUE THREAD

**Issue by clubdesarrolladores** [APY/APYDataGridBundle#259]
I have grid for AgreedDebt entity. It has several relationships with others entities.

I want show and filter for this field:

`AgreedDebt.PaymentAgreement.Service.Customer.name`

All works fine, except for this field (maybe for the deep of the relationship?).

First i try with annotations in entity:

```
@Grid\Column(
title="Customer", 
field="paymentAgreement.service.customer.name", 
operatorsVisible=false, filter="select", selectFrom="source")`
```

So i customize the query using  manipulateQuery (removing the annotation):

```
$qb->addSelect('_paymentAgreement_service_customer.name as customerName');
$qb->leftJoin('_paymentAgreement_service.customer', '_paymentAgreement_service_customer');
```

Adding a TextColumn

```
$grid->addColumn(new \APY\DataGridBundle\Grid\Column\TextColumn(array(
        'id' => 'customerName', 
        'title' => 'Customer', 
        'source' => true, 
        'field' => 'paymentAgreement_service.customer.name'
        )));
```

Now my problem is the filter and order, it just dont work:

[Semantical Error] line 0, col 589 near 'customerName': Error: 'customerName' is already defined. 

And changing the column id:

```
$grid->addColumn(new \APY\DataGridBundle\Grid\Column\TextColumn(array(
        'id' => 'customer_name', 
        'title' => 'Customer', 
        'source' => true, 
        'field' => 'paymentAgreement_service.customer.name'
        )));
```

This error:

[Semantical Error] line 0, col 737 near '_paymentAgreement_service': Error: Class WebFactory\SaleBundle\Entity\AgreedDebt has no association named paymentAgreement_service 

How i must define de Customer Name field in the grid?

**Comment by RodolVelasco** [comment]
How do @clubdesarrolladores generate de dql from his code? I want to do this for debugging purpouse.

**Comment by Abhoryo** [comment]
In the entity classe, you can perform a getDQL on the query builder before the execution
