### ISSUE TITLE
Handle multiple grids on the same page

### ISSUE THREAD

**Issue by stanislavprokopov** [APY/APYDataGridBundle#288]
According to the example on the "Handle multiple grids on the same page" documentation page, you can write something like this:

```php
if ($grid->isReadyForRedirect() || $grid2->isReadyForRedirect() )
{
    if ($grid->isReadyForExport())
    {
        return $grid->getExportResponse();
    }

    if ($grid2->isReadyForExport())
    {
        return $grid2->getExportResponse();
    }

    // Url is the same for the grids
    return new RedirectResponse($grid->getRouteUrl());
}
```

But actually if you try to do this it will not work, because the `getExportResponse` method is declared as `protected function getExportResponse()`.

###### Update:

The example with the GridManager wont work too:

```php
if ($gridManager->isReadyForRedirect())
{
    if ($gridManager->isReadyForExport())
    {
        return $gridManager->getExportResponse();
    }

    return new RedirectResponse($gridManager->getRouteUrl());
}
```

The GridManager doesnt have a `getExportResponse` method.

Link: https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/multi_grid_manager.md

**Comment by qferr** [comment]
Documentation is right for the master, the method `Grid::getExportResponse` is public.

**Comment by qferr** [comment]
Sorry, the method `GridManager::getExportResponse()` does not exit.
