### ISSUE TITLE
Custom column with apydatagridbundle

### ISSUE THREAD

**Issue by sedigo** [APY/APYDataGridBundle#334]
Hi, I have a grid with textcolumn and ActionsColumn. I would like to add one custom column that will have a custom size(similar to the actionscolumn) but to which I can bind an html link(as I can do with my textcolumn) instead of a controller (as it is with actionscolumn). I can't use a textcolumn because it will come with predefined size as for the rest of the column. 
I Hope someone can tell me how to create a custom text column that will have its own size. thank you

example: 
$customer_status->manipulateRenderCell(function($value, $row, $router) use ($ca) {
then I return an html with  onclick="$(\'#'.$unique_id.'\').modal(); 

this is what I do with my textcolumn. Would like either to do the same with my actioncolumn or create a custom column with custom size.

**Comment by doncamalote** [comment]
me esta pasando lo mismo...
fragmento de codigo.
{% block grid_column_id_nro_de_sol_cell %}
    <a href="{{ url('derivacion_show', {'id': row.field('id') }) }}">{{ value }}</a> {#{{row.field('id')}}#}
 {% endblock grid_column_id_nro_de_sol_cell %}

no me reconoce el id
