### ISSUE TITLE
Default Order by multiple columns?

### ISSUE THREAD

**Issue by userfriendly** [APY/APYDataGridBundle#344]
Hi there!

The docs have an example using a default ORDER BY with only one column, which I figure is enough in most cases.

But can I somehow add an additional default ORDER BY, as in "order by this column first, then order the result by that one"?

Cheers!

**Comment by Develle** [comment]
@nchagrass  this works but how to keep this order in export ?

**Comment by nchagrass** [comment]
@Develle I did not update that but this is wrong if you ask for a different order on the front-end (it will be overwritten by this bit, you will have to get the orders, read which one exists and add it if not.)
I did not nothing with the export but my guess is you will have to extend a class and get access to the source and manipulate the query again.

**Comment by Abhoryo** [comment]
Use the initQueryBuilder on entity source.
