### ISSUE TITLE
Ajax Search - Duplicate headers

### ISSUE THREAD

**Issue by nacho1982** [APY/APYDataGridBundle#404]
Hi. My question is this. 
I have a grid ajax, which does good order, the reset, everything. But when I want to make an external search, I replicate all header objects. The search does it well, but replicated N times the headers.
Would you know how I can avoid that?
Thank you for your consideration.

**Comment by Abhoryo** [comment]
to reset a grid with an url, add the key REQUEST_QUERY_RESET to your query parameters
