### ISSUE TITLE
Disable filtering

### ISSUE THREAD

**Issue by sstok** [APY/APYDataGridBundle#414]
processRequestFilters() is always executed, even when showFilters is disabled.
Should we skip the processRequestFilters() method call when showFilters is false?

I'd like to use a custom filtering system which actually modifies the Query in Source, so looping trough all the column for filtering is considered overhead for me.

**Comment by hmert** [comment]
https://github.com/APY/APYDataGridBundle/blob/master/Grid/Grid.php#L137
