### ISSUE TITLE
Query Result Caching

### ISSUE THREAD

**Issue by awolder** [APY/APYDataGridBundle#417]
Hi,
  Is there any way to do query result caching?  The problem we are facing is as follows: 

Situation:  We have an application that audits support cases.  To do this we run a query on our case table using the mysql rand() function ( a DQL query using a vector source) , and display the results using the grid.  This way, every time someone loads the application, they are presented with a random set of cases (100 cases displayed at a time).

Problem:  From the pool of randomly returned cases, when using the grid filters or pagination buttons, the query is re-issued and  a new random set is generated giving an unexpected result.  Lets say out of the original pool of cases, the user notes that case owner 'John Doe' appears in 5 of the cases.  The user then sets the grid filter for 'John Doe'.  The filter re-issues the query, and because of the rand function 'John Doe' may not appear at all in the new set. We would like to maintain the original query result throughout the session or until the user reloads the page.

Well I hope the issue is clear.  Any suggestions are welcome :)

**Comment by qferr** [comment]
@hmert This is a new feature no ?

**Comment by hmert** [comment]
I think, this bundle should relay on Doctrine(+cache). Cache is not our feature.

**Comment by qferr** [comment]
If you want a cache please use the doctrine cache.
