### ISSUE TITLE
Issue Sort and Filter when use Concat and Group_Concat manipulateQuery

### ISSUE THREAD

**Issue by ironmask285** [APY/APYDataGridBundle#425]
Hi Everyone, Today we need some guidance from your expertise. We are using APY Datagrid Bundle in our project. In some specific cases, we use a query like this:

SELECT 
  c0_.first_name AS first_name0, 
  c0_.email AS email1, 
  c0_.phone AS phone2, 
  c0_.last_name AS last_name3, 
  c0_.storefront_id AS storefront_id4, 
  c0_.reset_password_id AS reset_password_id5, 
  c0_.id AS id6, 
  c0_.created AS created7, 
  c0_.updated AS updated8, 
  CONCAT_WS(
    ' ', c0_.first_name, c0_.last_name
  ) AS sclr9, 
  CONCAT_WS(
    ' ', 
    CONCAT_WS(' ', a1_.line1, a1_.line2), 
    c2_.name
  ) AS sclr10, 
  GROUP_CONCAT(
    CONCAT(c3_.code, '-', c3_.id)
  ) AS sclr11 
FROM 
  customer c0_ 
  LEFT JOIN customer_address c4_ ON c0_.id = c4_.customer_id 
  LEFT JOIN address a1_ ON c4_.address_id = a1_.id 
  LEFT JOIN country c2_ ON a1_.country_id = c2_.id 
  LEFT JOIN customer_order c3_ ON c0_.id = c3_.customer_id 
GROUP BY 
  c0_.id 
LIMIT 
  20

In this case, we use 'sclr9' alias for Full Name field and we want to sort by this field with APY Datagrid. But we still cannot find a way to add conditions for aliases to Datagrid. Do you have any ideas to help us for this issue?

:) 

Best regards,

**Comment by link365dev** [comment]
What was the resolution?
