### ISSUE TITLE
getTotalCount() in Source/Entity.php is causing "Allowed memory ... exhausted"

### ISSUE THREAD

**Issue by jclopez** [APY/APYDataGridBundle#475]
We are trying to load 30,011 records (entities with relations to other entities) and this is causing the following error "PHP message: PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted".

We debugged APYDataGridBundle and found out that Grid/Source/Entity.php file on getTotalCount() is breaking in line # 467

The query doing the count `$data = $countQuery->getScalarResult();` is returning an array with all the records then is executing the following lines in order to obtain the count:

`$data = array_map('current', $data);`
`$count = array_sum($data);`

Shouldn't have better performance when override the `$countQuery` query :

'SELECT count(DISTINCT t0_.id) AS sclr0, p1_.name AS name1, p2_.name AS name2, t3_.name AS name3, f4_.firstname AS firstname4, f4_.lastname AS lastname5, f4_.id AS id6, l5_.name AS name7, l5_.enabled AS enabled8, f6_.firstname AS firstname9, f6_.lastname AS lastname10, f6_.id AS id11, f7_.firstname AS firstname12, f7_.lastname AS lastname13, c8_.name AS name14, s9_.name AS name15 FROM ticket t0_ LEFT JOIN priority p1_ ON t0_.priority_id = p1_.id LEFT JOIN priority p2_ ON t0_.importance_id = p2_.id LEFT JOIN team t3_ ON t0_.team_id = t3_.id LEFT JOIN fos_user f4_ ON t0_.requested_id = f4_.id LEFT JOIN location l5_ ON t0_.location_id = l5_.id LEFT JOIN fos_user f6_ ON t0_.assigned_id = f6_.id LEFT JOIN fos_user f7_ ON t0_.owner_id = f7_.id LEFT JOIN category c8_ ON t0_.category_id = c8_.id LEFT JOIN status s9_ ON t0_.status_id = s9_.id LEFT JOIN status s10_ ON t0_.status_id = s10_.id LEFT JOIN team t11_ ON t0_.team_id = t11_.id WHERE t0_.canceled IS NULL AND t11_.id = ? AND t11_.enabled = 1 GROUP BY p1_.name, p2_.name, t3_.name, f4_.firstname, f4_.lastname, f4_.id, l5_.name, l5_.enabled, f6_.firstname, f6_.lastname, f6_.id, f7_.firstname, f7_.lastname, c8_.name, s9_.name, t0_.id'

for something like this: 

'SELECT count(DISTINCT t0_.id) AS sclr0 FROM ticket t0_ LEFT JOIN priority p1_ ON t0_.priority_id = p1_.id LEFT JOIN priority p2_ ON t0_.importance_id = p2_.id LEFT JOIN team t3_ ON t0_.team_id = t3_.id LEFT JOIN fos_user f4_ ON t0_.requested_id = f4_.id LEFT JOIN location l5_ ON t0_.location_id = l5_.id LEFT JOIN fos_user f6_ ON t0_.assigned_id = f6_.id LEFT JOIN fos_user f7_ ON t0_.owner_id = f7_.id LEFT JOIN category c8_ ON t0_.category_id = c8_.id LEFT JOIN status s9_ ON t0_.status_id = s9_.id LEFT JOIN status s10_ ON t0_.status_id = s10_.id LEFT JOIN team t11_ ON t0_.team_id = t11_.id WHERE t0_.canceled IS NULL AND t11_.id = ? AND t11_.enabled = 1'

returning just only the count and not all the results ...

Thanks

**Comment by asgarciap** [comment]
Hi, is there any advance on this issue?
I'm getting the same error, (PHP memory exausted) using the grid with an entity that maps a mysql table with 130K records.
@jclopez's solution works for me to.
Thanks!
