### ISSUE TITLE
Filter in multi column

### ISSUE THREAD

**Issue by pastorale** [APY/APYDataGridBundle#484]
Hi !
I have a table and I would like to filter in multi column.I have try more solutions but it's not working.Can you help me ? Is this feture  possible ? 
$grid->getColumn('column1','column2','column3')->setTitle(Label())->setOperators($operation)->setFilterable(true)->setFilterType('input')->setOperatorsVisible(false);

**Comment by RodolVelasco** [comment]
Hey guys!

I have a question about manipulate query. Can I use something like multiple andwhere and YEAR function from mysql. Here is my example

```
$source->manipulateQuery(
			    function ($query) use($years)
			    {
			    	$date_cur = new \DateTime();
					$hoy = $date_cur->format('Y\-m\-d\ ');
					
			        $query->resetDQLPart("where");
					$query->andWhere("_a.fechaFin >= (:hoy)")->setParameter("hoy", $hoy);
					$query->andWhere("YEAR(_a.fechaInicio) = (:years)")->setParameter("years", $years);
			    }
			);
```

**Comment by Abhoryo** [comment]
Yes you can

**Comment by bawae** [comment]
hello Abhoryo, i think there is a problem with "setDataJunction(Column::DATA_DISJUNCTION)", i get always AND in my filters fields.
