### ISSUE TITLE
GroupConcat Like Problem

### ISSUE THREAD

**Issue by alibahsisoglu** [APY/APYDataGridBundle#491]
Hi,

I have a problem with group concat dql function. I saw group concat field in table normal but when I want to filter group concat field with like I get an error like this.

``` php
[Syntax Error] line 0, col 713: Error: Expected '.' or '(', got
'items::barcode::skuCode::skuCode:GroupConcat'
```

How could I solve this problem?

Thank you

**Comment by kaamaa** [comment]
Hi Abhoryo,

just read your recommendation above and made it work in my application, however visible"false" doesn't work on the second column, seeing both columns now. Any hints?

Best
Martin

**Comment by kaamaa** [comment]
Hi Abhoryo,

if the problem is solved with Symphony 2.4 or later, how can I enable the like operator in the Datagrid?

Best
Martin

**Comment by kaamaa** [comment]
...found it in 

Column.PHP => public function getOperators()

however, I can't confirm that the underlying problem is solved in symfony 2.4 or higher as mentioned by alibahsisoglu, the problem still exists in symphony 2.6.

Or have I missed anything?

Best
Martin

**Comment by Abhoryo** [comment]
If you have ORM 2.5 it should work.

**Comment by kaamaa** [comment]
not sure why, but problem still exists for me with the following versions:

installed:
  beberlei/DoctrineExtensions          dev-master 6f4a04e A set of extensions...
  doctrine/annotations                 v1.2.4             Docblock Annotation...
  doctrine/cache                       v1.4.1             Caching library off...
  doctrine/collections                 v1.3.0             Collections Abstrac...
  doctrine/common                      v2.5.0             Common Library for ...
  doctrine/dbal                        v2.5.1             Database Abstractio...
  doctrine/doctrine-bundle             v1.4.0             Symfony DoctrineBundle
  doctrine/doctrine-cache-bundle       v1.0.1             Symfony2 Bundle for...
  doctrine/inflector                   v1.0.1             Common String Manip...
  doctrine/instantiator                1.0.4              A small, lightweigh...
  doctrine/lexer                       v1.0.1             Base library for a ...
  doctrine/orm                         v2.5.0             Object-Relational-M...
  incenteev/composer-parameter-handler v2.1.0             Composer script han...
  jdorn/sql-formatter                  v1.2.17            a PHP SQL highlight...
  kriswallsmith/assetic                v1.2.1             Asset Management fo...
  monolog/monolog                      1.13.1             Sends your logs to ...
  psr/log                              1.0.0              Common interface fo...
  sensio/distribution-bundle           v2.3.16            The base bundle for...

**Comment by kaamaa** [comment]
By the way, updating to the latest version of the datagribundle today brought the following error on all Grids I'm using:

An exception has been thrown during the rendering of a template ("No metadata information has been found for....

Reverting back to the former version fixed the problem.

Best
Martin
