### ISSUE TITLE
Discriminator

### ISSUE THREAD

**Issue by patie** [APY/APYDataGridBundle#495]
Hi,

is there way how to grid identify which discriminator class is in using ? Someting like instanceof. 

In case when i display grid with parent model class (with all discriminator children) and i want distinguish which discriminator is current row.

i hope its clear

**Comment by plfort** [comment]
I am also interested by this issue

**Comment by Abhoryo** [comment]
Thx @bigfoot90 for the link

The discriminator is stored in a column so I suppose you just have to show this column.

**Comment by plfort** [comment]
I think the column is not accessible with the ORM (it is not mapped), the only way to distinguish the type is to use "INSTANCE OF" keyword in query
