### ISSUE TITLE
One filter field on multi columns

### ISSUE THREAD

**Issue by Bomere** [APY/APYDataGridBundle#608]
Hello,

I try to add a google like input on my datagrid.
It's possible to do that ? 

I have try to add a new column and get in all values from others columns but if I want to filter on this new column, it isn't work... 

Can you show me the way ?

Thank you.

**Comment by bawae** [comment]
Hello, i'm trying to do the same thing for my grids. Can you give more details please.

**Comment by Bomere** [comment]
Hello, 

I wil try to help you

controller:
```php
protected function getAnalGrid (Request $request, $route)
    {
        $source = new Entity('DbBundle:Analyses');

        $grid = $this->get('grid');

 

```

**Comment by bawae** [comment]
thank you very much, i will try it  :-)
