### ISSUE TITLE
MassAction - selectAll

### ISSUE THREAD

**Issue by rflorent** [APY/APYDataGridBundle#638]
Hello,
I have to use mass action in my project
There is two select button for mass action : "select visible" and "select all".
I guess "select visible" button will select rows displayed and "select all" button will select all result from query with filters.
Select visible button works fine, but I don't know how retrieve all primary keys when I use "select all".
I have allPrimaryKey == 1 in my controller, but how can I get all primary keys or query filtered ?

Thanks

**Comment by plfort** [comment]
@rflorent can you provide advanced examples ?
I agree with you, I think the grid sould do the job.

**Comment by rflorent** [comment]
Hello,

https://gist.github.com/rflorent/88f4c08a14986c95afed

**Comment by plfort** [comment]
Thank you very much !

**Comment by plfort** [comment]
@rflorent what do think of this PR  #718 ?
