### ISSUE TITLE
Master-Detail 

### ISSUE THREAD

**Issue by pietro2328** [APY/APYDataGridBundle#651]
Hi.
I would like to create a grid with the Master-Detail functionality.
When I click on a link, a detail grid should appear.
This can simulate it with jquery, but don't want to be on different "div" . This functionality is very popular in the jquery grid. Can simulate this behavior?.

Tks.

**Comment by Abhoryo** [comment]
You can simply show an other grid on a row click. You just have to deal with the insert after your row.
