### ISSUE TITLE
Caractère spéciaux Export Excel

### ISSUE THREAD

**Issue by Ahmed1984** [APY/APYDataGridBundle#655]
Bonjour @Abhoryo ,

j'ai un problème d'affichage des caractère spéciaux lors de l'export excel , les valeurs sont stockées dans un fichier yml pour une entité grid 
values: { 0:Aucun, 1:de 1€ à 150k€, 2:de 150k€ à 400k€}

pour la valeur 1  "1€ à 150k€,"      il  affiche dans excel        "de 1â¬ Ã  150kâ¬".

merci d'avance pour ton aide

Très cordialement

**Comment by hmert** [comment]
Le temps est déjà passé. Non contemporaine 👋
