### ISSUE TITLE
Hide all columns and filters by default

### ISSUE THREAD

**Issue by bigfoot90** [APY/APYDataGridBundle#668]
Implement `hide_by_default` option to hide all columns and filters by default.

My class looks like this currently _(omitting doctrine annotations for brevity)_:

``` php
/**
 * @GRID\Source(columns="id, firstName, lastName, full_name, phoneNumber, email")
 * @GRID\Column(id="full_name", type="join", title="Full name", columns={"lastName", "firstName"})
 */
abstract class Person implements PersonInterface, TargetInterface, CreatorInterface
{
    /**
     * @GRID\Column(visible=false, filterable=false)
     */
    protected $id;

    /**
     * @GRID\Column(visible=false, filterable=false)
     */
    protected $firstName;

    /**
     * @GRID\Column(visible=false, filterable=false)
     */
    protected $lastName;

    /**
     * @GRID\Column(visible=true, filterable=true)
     */
    protected $email;

    /**
     * @GRID\Column(visible=true, filterable=true)
     */
    protected $phoneNumber;

    /**
     * @GRID\Column(visible=false, filterable=false)
     */
    protected $notes;

    /**
     * @GRID\Column(visible=false, filterable=false)
     */
    protected $createdOn;

    //// Setters and getters
    //// ...
}
```

With `hide_by_default` option it became short:

``` php
/**
 * @GRID\Column(id="full_name", type="join", title="Full name", columns={"lastName", "firstName"})
 */
abstract class Person implements PersonInterface, TargetInterface, CreatorInterface
{
    protected $id;

    protected $firstName;

    protected $lastName;

    /**
     * @GRID\Column(visible=true, filterable=true)
     */
    protected $email;

    /**
     * @GRID\Column(visible=true, filterable=true)
     */
    protected $phoneNumber;

    protected $notes;

    protected $createdOn;

    //// Setters and getters
    //// ...
}
```

**Comment by hmert** [comment]
@bigfoot90 it looks nice feature. if you have time, propose a PR.

**Comment by bigfoot90** [comment]
I'm sorry, I do not work on this project from some time.
I leave this PR open, so somebody can implement this in future.

**Comment by hmert** [comment]
ok thank you for your past efforts.

**Comment by Abhoryo** [comment]
It should be an attribute of the source annotation like filterable and sortable which define the default behavior of columns.
https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/columns_configuration/annotations/source_annotation.md

**Comment by qferr** [comment]
@bigfoot90 I think it is not necessary to implement this option. Why you configure columns that are not to be displayed? Why not set the grid configuration like this:

```
@GRID\Source(columns="id, full_name, email, phoneNumber")
```

@hmert @Abhoryo By default, only the configured columns are visible and filterable ?

**Comment by Abhoryo** [comment]
If a source:columns attribute is defined, only these columns are visible and not filterable by default.
If no source:columns is defined, each property of the entity is a visible column by default.
source:columns attribute is meant to define which columns we need in the grid as data source not necessarily making a column with the data. It can be used to generate a link, define the color of the row, define the visibility of a column, etc...
