### ISSUE TITLE
Problem adding permanentFilter to relation

### ISSUE THREAD

**Issue by murilolobato** [APY/APYDataGridBundle#670]
I have a Product entity that is related to a Profile entity. Product has a property called $profile, that can contain NULL or a Profile instance.

The grid that displays the Products list, I want to list only the products aren't related to a profile, I'm using the following code without success:

    $grid = $this->get('grid');
    $grid->setSource(new Source('MyBundle:Product'));

    $grid->setPermanentFilters(array(
        'profile' => array('operator' => 'isNull'),
    ));

Is this a limitation or I'm missing something ?

**Comment by Abhoryo** [comment]
It should work.
