### ISSUE TITLE
Many to many error

### ISSUE THREAD

**Issue by Grazulex** [APY/APYDataGridBundle#682]
Hello,

I try to render a Many 2 Many relation but the script render for each value of the relation a new row.
When I try the GroupConcat function, I have a error :
```
[Syntax Error] line 0, col 328: Error: Expected known function, got 'GroupConcat' 
```
My code is :
```
/**
 * Modulesteps
 *
 * GRID\Source(columns="id,module.milestone.project.name, module.milestone.name, module.name, step.name, step.required, step.type, startDate, stopDate, users.initial:GroupConcat")
 */
class Modulesteps

    /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="modulesteps")
     * @GRID\Column(field="users.initial:GroupConcat", title="Ressources")
     */
    protected $users; 
```

Where is the error ?

**Comment by Grazulex** [comment]
Hello, I have find a part of the issue, GroupConcat is not standart in Doctrine and we need to install this extension (https://github.com/beberlei/DoctrineExtensions/tree/master/lib/DoctrineExtensions/Query/Mysql).
Now I don't have any error anymore but the result of the query is wrong... from 29 rows I have now 3 rows (each for each user name and not more for each record).....can we do only a GroupConcat on one fields and not on the source ?

**Comment by Abhoryo** [comment]
When you use an aggregation function like GroupConcat, it's logic that your number of row decrease.
Choose the right column to perform a group by.
