### ISSUE TITLE
How to populate the selector from callback

### ISSUE THREAD

**Issue by grekpg** [APY/APYDataGridBundle#688]
hi is possible to populate selector from callback ?

i found option from source - what is source ? 
i looking something like that 
<?php
class a{
/**
 * @GRID\Column(filter="select", selectFrom="callback?", calback="a:getTypes")
 */
protected $type;
...

or other way if i have values in array i can puth it in grid controller 

$grid->get('type')->setValues() ?

**Comment by Abhoryo** [comment]
If you do that, you can't filter the column because, these values are not the real values of a column.

**Comment by grekpg** [comment]
in a filter query builder you can add if selectFrom == callback -> reverse trasform then aply filter.

**Comment by Abhoryo** [comment]
What getTypes() return in your case ?
