### ISSUE TITLE
Multiple grid but one entity

### ISSUE THREAD

**Issue by hieros** [APY/APYDataGridBundle#689]
Hello,
What is the best way to build several grid based on the same entity with different settings?
Can we still use a yml file to define different settings and how to use them?
Thank you in advance.

http://afsy.fr/avent/2013/04-utilisez-apydatagridbundle-pour-des-listings-impeccables
```
"php app/console apydatagrid:generate:grid ACSEOCalendrierBundle:Article default"

    Le premier argument (ACSEOCalendrierBundle:Article) permet de préciser l'entité sur laquelle nous travaillons.
    Le deuxième argument (default) permet de nommer la grille. Cela pourra être utilisé pour créer des grilles reposant sur la même entité mais avec des paramétrages différents.

```

**Comment by Abhoryo** [comment]
Superbe tuto. Ca donne envie sur le papier :D

You can use yml when a certain pull request will be merge.

From now, you can just set a unique source in php and clone it when the parameters aren't the same.
