### ISSUE TITLE
Grid Ajax

### ISSUE THREAD

**Issue by jjamaral** [APY/APYDataGridBundle#690]
Hi all!

First of all, I wanna congratulate all contributors for this awesome bundle!

I have an issue with Ajax Grid load: every time grid is loaded (sorting, filtering, etc) all HTML are loaded, instead of only grid HTML. Do you know why? Im missing something?

Thanks in advance!

**Comment by bladi87** [comment]
Hello,
I have the same problem.
I think one solution is something like this: (based on this issue https://github.com/Abhoryo/APYDataGridBundle/issues/258)

```return $grid->getGridResponse($request->isXmlHttpRequest() ? 'MyProjectMyBundle::my_grid.html.twig' : 'MyProjectMyBundle::default.html.twig');```

What you have to do is to put the grid alone in a template (my_grid.twig.html) and include it in a global template (default.twig.html). Render the whole page with the global template when you first call your page and render only the grid template when it's an XmlHttpRequest.

**Comment by Abhoryo** [comment]
@bladi87  is right.
I agree that it isn't a optimize solution :(

**Comment by jjamaral** [comment]
@bladi87  thank you for your answer.
Yes, its a solution indeed. If I found another one, I'll share here.

**Comment by aftabnaveed** [comment]
thank you @bladi87  that solution worked for me.
