### ISSUE TITLE
RowAction: delete row action by POST/DELETE method

### ISSUE THREAD

**Issue by jjamaral** [APY/APYDataGridBundle#692]
Hi!

Do you know if its possible to add parameters to route, in order to submit a request with POST or DELETE method, instead a simple GET request?

Example:
```
$deleteAction = new RowAction('Delete', 'client_delete', $confirm = true);
$grid->addRowAction($deleteAction);
```

Thanks in advance!

**Comment by Abhoryo** [comment]
a row action is a simple link.
You can use the mass action for post request/
Else you can embed small form on the template of a rowaction to perform over request type.

**Comment by jjamaral** [comment]
Got it!
Thank you for fast answer @Abhoryo
