### ISSUE TITLE
Problem with ManipulateRender and overwrite a Template

### ISSUE THREAD

**Issue by pietro2328** [APY/APYDataGridBundle#693]
Hello.
I've a problem, when I use the ManipulateRender sentence.
In my controller, for example:

 $myRowAction = new RowAction('associate', route, false, '_self', array('class' => 'associate'));      
       $myRowAction->manipulateRender(function ($action, $row) {
           if(($row->getField('validate') <> 0))
        {
            $action->setTitle('associate');
        }else{
            $action->setTitle('disabled');            
}

TWIG:
<td>{{ grid(first,'SourceBundle:Maq:TemplateMaq.html.twig')}}</td>       

-TEMPLATE:

{% extends 'APYDataGridBundle::blocks_js.jquery.html.twig' %}
    
{% block grid_column_actions_cell %}
    {% for action in column.rowActions %}        
        {% if action.title=="associate" %}            
            <a rowid="{{row.field('id')}}" {% for name, value in action.attributes %} {{ name }}="{{ value }}" {% endfor %}>{{ action.title|trans }}</a>{{ column.separator|raw }}
        {% endif %}                                 
    {% endfor %} 
{% endblock grid_column_actions_cell %} 

If I don't override the template, I don't have any problem, but I need to use it in another action in JS.
Thanks!

**Comment by Abhoryo** [comment]
I can't help you without the error.

**Comment by pietro2328** [comment]
When I use this code, the ManipulateRender and overwrite the template with the block {% block grid_column_actions_cell %} doesn't run. In the grid, the action button "associate" or "disabled" are not visible.
But, if I don't overwrite the template, with {% block grid_column_actions_cell %}, there aren't any problem.
I need overwrite the template, because then I use in Javascript to another events.
Can you help me?

**Comment by Abhoryo** [comment]
Did you add the rowAction to your grid ?

**Comment by pietro2328** [comment]
Of course.  In my controller 
grid-> addRowAction ($ myRowAction)

But if I overwrite the template, this statement did not work (ManipulateRender).

**Comment by Abhoryo** [comment]
You have to return the action if the ManipulateRender function. (See the example in the doc)
