### ISSUE TITLE
manytomany string_agg: filter raise exception

### ISSUE THREAD

**Issue by FredDut** [APY/APYDataGridBundle#702]
Hello,
I've  a manytomany relation (postgres db) and I use string_agg, as mentioned in another issue.
In my entity, I have
@GRID\Source(columns="id, nom, telephone, mel, sites.nom:string_agg:_", groupBy={"id"}, filterable=true)
The grid shows the column, but if I try to filter, I get this exception:

> An exception occurred while executing 'SELECT s0_.id AS id0, s0_.nom AS nom1, s0_.telephone > AS telephone2, s0_.mel AS mel3, string_agg(s1_.nom, '_') AS sclr4 FROM structure s0_ LEFT JOIN sites_structures s2_ ON s0_.id = s2_.id_structure LEFT JOIN site s1_ ON s1_.id = s2_.id_site GROUP BY s0_.id HAVING sclr4 = ? LIMIT 10' with params ["Paris"]:

>SQLSTATE[42703]: Undefined column: 7 ERROR: column "sclr4" does not exist
LINE 1: ...1_ ON s1_.id = s2_.id_site GROUP BY s0_.id HAVING sclr4 = $1...

Aren't string_agg columns filterables?

In another context, if I try to filter the data with setData before rendering the grid I get

>FatalErrorException: Error: Class 'Symfony\Component\Form\Exception\PropertyAccessDeniedException' not found in /myproject/vendor/apy/datagrid-bundle/Grid/Source/Source.php line 212

There are two problems: the PropertyAccessDeniedException removed in SF 2.3 and the string_agg problem.

**Comment by Abhoryo** [comment]
Check your doctrine version. I think you should have at least the 2.5 version.

If you know what exception we can use instead, you can make a PR. Thanks.

**Comment by FredDut** [comment]
Hello,

I run an SF2.3 updated version with
>doctrine/annotations                 v1.2.4
>doctrine/cache                       v1.4.1
>doctrine/collections                 v1.3.0
>doctrine/common                      v2.5.0
>doctrine/data-fixtures               v1.1.1
>doctrine/dbal                        v2.4.4
>doctrine/doctrine-bundle             v1.5.0
>doctrine/doctrine-cache-bundle       v1.0.1
>doctrine/doctrine-fixtures-bundle    v2.2.0
>doctrine/inflector                   v1.0.1
>doctrine/lexer                       v1.0.1
>doctrine/orm                         v2.4.7

What part of doctrine should be in 2.5? common, orm, dbal?

Thanks

**Comment by FredDut** [comment]
Hello ,
I finally upgrade to SF 2.7 and doctrine 2.5.
But the error when I try filter remains:
>An exception occurred while executing 'SELECT s0_.id AS id_0, s0_.nom AS nom_1, s0_.telephone AS telephone_2, s0_.mel AS mel_3, string_agg(s1_.nom, '_') AS sclr_4 FROM structure s0_ LEFT JOIN sites_structures s2_ ON s0_.id = s2_.id_structure LEFT JOIN site s1_ ON s1_.id = s2_.id_site GROUP BY s0_.id HAVING sclr_4 = ? ORDER BY s0_.nom ASC LIMIT 10' with params ["an"]:

>SQLSTATE[42703]: Undefined column: 7 ERREUR: la colonne « sclr_4 » n'existe pas
>LINE 1: ...1_ ON s1_.id = s2_.id_site GROUP BY s0_.id HAVING sclr_4 = $...

Any idea?
Best regards
