### ISSUE TITLE
Rechargement ajax entraîne rechargement du template twig complet

### ISSUE THREAD

**Issue by SylvainSimon** [APY/APYDataGridBundle#703]
Bonjour,

Lorsque je veut effectuer une action sur mon tableau (Changement de page, recherche), le rechargement ajax me redraw toute la fenêtre à l'endroit du tableau, ça inclus le header, le footer et tout le contenu..

Je fait un render tout simple d'un objet grid dans mon template
Ce que je veut c'est que ce soit juste mon tableau qui se recharge, pas toute la page qui se duplique...

{% extends "AxessCoreBundle:Base:basePwmed.html.twig" %}

{% block body %}

    <div class="panel panel-default">
        <div class="panel-heading">Accueil</div>
        <div class="panel-body">

            <div class="alert alert-success" role="alert">
                <a href="#" class="alert-link">Ceci est un message</a>
            </div>
            <div class="alert alert-info" role="alert">
                <a href="#" class="alert-link">Ceci est un message</a>
            </div>
            <div class="alert alert-warning" role="alert">
                <a href="#" class="alert-link">Ceci est un message</a>
            </div>
            <div class="alert alert-danger" role="alert">
                <a href="#" class="alert-link">Ceci est un message</a>
            </div>

            
            {{ grid(grid) }}
            
            Vous êtes sur le sous-domaine {{ domaine }}
        </div>
    </div>

{% endblock %}

Faut-il rendre ce grid dans un template à part ou c'est moi qui fait une erreur de compréhension ?

Cordialement,

![image](https://cloud.githubusercontent.com/assets/11244274/6777863/f80110e6-d14d-11e4-855a-d25fb94fc565.png)

**Comment by Abhoryo** [comment]
Oui, ca recharge tout par défaut, regarde d'autres issues où il est expliqué comment faire.
https://github.com/Abhoryo/APYDataGridBundle/issues/258#issuecomment-9321484
