### ISSUE TITLE
Change order of filters in filter box

### ISSUE THREAD

**Issue by gribos** [APY/APYDataGridBundle#708]
Hello,
How can i change the order of filters which are displayed in filter box ? I want change only order of my filters in search box without changing order columns in grid.

**Comment by vialcollet** [comment]
Hi I am interested to understand how we can do this too without having to entirely write a template with each field.
Thanks

**Comment by Abhoryo** [comment]
@vialcollet You have to override the filters template.
What you can do to make easier the task is to use a list of your ordered columns to render this filters like you want.
