### ISSUE TITLE
Problem overriding cell render block

### ISSUE THREAD

**Issue by otstrel** [APY/APYDataGridBundle#710]
Hello!

I'm trying to override cell block without any luck. I narrowed it down to the below code. Controller:
```
$grid = $this->get('grid');
$grid->setSource(new Vector(array(array('a'=>1, 'b'=>2), array('a'=>3, 'b'=>4))));
return $grid->getGridResponse('default/tasks.html.twig');
```
Here is my tasks.html.twig:
```
{{ grid(grid, 'default/tasks_grid.html.twig') }}
```
Here is my tasks_grid.html.twig:
```
{% extends 'APYDataGridBundle::blocks.html.twig' %}

{% block grid_column_id_a_cell %}
X
{% endblock %}
```
I expect 'a' column values to be rendered as X but it still shows original values - 1 and 3. I carefully studied documentation but cannot seem to find what the problem is. Most confusing thing is that overriding block grid appears to be working fine - {% block grid%}{% endblock %} renders empty page as expected.

Regards,

otstrel

**Comment by b-durand** [comment]
I have the same problem. I want to override the block of a filter. The Twig Helper does not found the block with hasBlock method of TwigTemplate. Bug with extends?
I use Twig v1.18.0.

**Comment by b-durand** [comment]
@otstrel try grid_column_id_b_cell instead of grid_column_id_a_cell :wink:  I think that you can't override cell of primary column.

My problem is not the same: I want to override external filters in order to replace empty label by all.

**Comment by Abhoryo** [comment]
If your grid have an id try `grid_<grid_id>_column_a_cell`
