### ISSUE TITLE
OneToMany relation - manipulateQuery alias

### ISSUE THREAD

**Issue by jjamaral** [APY/APYDataGridBundle#715]
Hi there!

I'm getting a small issue regarding getting a field from relation in *manipulateQuery*.

**Background:**
I have this three entities: **Ticket**, **Machine** and **Company**.
One company have multiple machines. And one machine have multiple tickets.

I want **list all tickets from one specific company** (getting from session).
So, I think this will work (but not):
```
$source = new Entity('MachineBundle:Ticket');
$source->manipulateQuery(
    function ($query) use ($tableAlias) {
        $query->andWhere('_machine.company = ' . $this->getUser()->getCompany()->getId());
    }
);
```

**Ticket Entity**
```
/**
* @var integer
*
* @ORM\ManyToOne(targetEntity="AppBundle\MachineBundle\Entity\Machine", inversedBy="tickets")
* @ORM\JoinColumn(name="machine_id", referencedColumnName="id")
* @Assert\NotBlank()
* @GRID\Column(
*  field="machine.company",
* )
*/
private $machine;
```
On **@GRID\Source()** I have **machine.company** too.

I have another example **working**: listing all machines from one specific company:
```
$source = new Entity('MachineBundle:Machine');
$tableAlias = $source->getTableAlias();
$source->manipulateQuery(
    function ($query) use ($tableAlias){
        $query->andWhere($tableAlias . '.company = ' . $this->getUser()->getCompany()->getId());
    }
);
```
This example is working as expected. The first one, not.

Any tips?

Thanks in advance!

**Comment by Abhoryo** [comment]
You don't use the tableAlias in the first exemple.
