### ISSUE TITLE
Latest commit throws an metdata exception

### ISSUE THREAD

**Issue by vialcollet** [APY/APYDataGridBundle#720]
Hi there after updating to the latest dev-master, my Symfony 2.3 app is now throwing the following exception: No metadata information has been found.
I saw that this is due to the fact that if there is no annotation in a given entity/group.
I would suggest that such versions are properly tagged in order to avoid such issues.
If my understanding is correct, the only quick solution is to require 2.1.15, correct?
Thanks !

**Comment by Abhoryo** [comment]
Sorry for the mess

**Comment by npotier** [comment]
Hi @vialcollet thanks for the feedback. I'll try to reproduce this behaviour and fix it asap.

Nicolas.

**Comment by Tjeerd** [comment]
@Abhoryo: please release a new version equal to 2.1.15 asap! Every new install or update will now get a broken version!

**Comment by asgarciap** [comment]
Hi!
The last version is still broken at this point. Last night updated to 2.2.16 version failed with same error mentioned here.
Please, a new version will be nice!

**Comment by milan74sk** [comment]
When will be released fixed version please ?

**Comment by qferr** [comment]
#773

**Comment by qferr** [comment]
This issue does not exist in master. 

@APY/collaborators If we support the BC version 2.2, we should fix on this version.

**Comment by hmert** [comment]
yes, we should. Because 2.2 should not have a bug.

**Comment by hmert** [comment]
https://github.com/APY/APYDataGridBundle/releases/tag/2.2.17 this tag fixes
