### ISSUE TITLE
the views on readme are ugly

### ISSUE THREAD

**Issue by cordoval** [APY/APYDataGridBundle#721]
let's update the views on the readme please, they will encourage the usage of this

also @sstok perhaps you should do the same on https://github.com/rollerworks/rollerworks-datagrid :blush:

**Comment by Abhoryo** [comment]
Sorry, but I don't understand your point. Can you enlighten me?

**Comment by sstok** [comment]
The example images are outdated and should be updated to give a better impression.
Rollerworks-datagrid is unrelated to this project :)

**Comment by hmert** [comment]
We have dublicate issue for documentation. I'm closing this
