### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by zdrsoft** [APY/APYDataGridBundle#729]
While I was looking in the code I found one piece of the code, which could be improved.
Please take a look here:
File: Grid/Grid.php
Line: 807
    protected function processSessionData()
    {
        // Filters
        foreach ($this->columns as $column) {
            if (($data = $this->get($column->getId())) !== null) {
                $column->setData($data);
            }
        }

Take a look on $column, for each $column is set data, but $column object is not used or returned in the method processSessionData any more. Please, improve the code.
I hope this will help to be improved the code of this great bundle.

Best Regards
Zdravko

**Comment by qferr** [comment]
Wrong, columns are passed by reference.
