### ISSUE TITLE
manipulateQuery via closure can't receive data

### ISSUE THREAD

**Issue by marinsagovac** [APY/APYDataGridBundle#732]
On example it's show that via symfony request will not receive request variables from any form instead as fixed string/integer variable. Example not working on `$request_id` received to closure on manipulateQuery. How can I get `$request_id` instead of null?

	public function indexAction(Request $request)
	{
		$request_all = $request->request->all();
		// Ok received all arrays

		$request_id = $request_all['custom']['action']['id'];
		// Ok, received ID

		$fixed_id = (int)123;

		$source = new Entity('<bundlename>:<entity>');
		$tableAlias = $source->getTableAlias();

		$source->manipulateQuery(
		        function ($query) use ($tableAlias, $request_id){
				var_dump($request_id); // Null, not received ID
				var_dump($fixed_id); // Works
			}
	}

**Comment by qferr** [comment]
@marinsagovac Are you sure the variable `$request_id` is defined before being used in callback ? What is your php version ?

**Comment by qferr** [comment]
Closing as there is no feedback.
