### ISSUE TITLE
Multiple fields mapped to same entity

### ISSUE THREAD

**Issue by willjrcristo** [APY/APYDataGridBundle#736]
Hello,

Let's suppose: One product with two fields with same association. 

How to display the property name of each field in the grid?

@GRID\Source(columns="id, unit_of_measure.name, unit_of_measure.name")
class Product {
         id,
@ORM\... (targetEntity="unit_of_measure")
@GRID\Column(field="unit_of_measure.name", title="Buy")
         unit_of_measure_buy,
@ORM\... (targetEntity="unit_of_measure")
@GRID\Column(field="unit_of_measure.name", title="Sale")
         unit_of_measure_sale,
}

Also is wrong! 

What's?

Sorry if this question already exists, because I don't found.

**Comment by qferr** [comment]
@willjrcristo The configuration is wrong. Try this:

```php
/**
 * @GRID\Source(columns="id, unit_of_measure_buy.name, unit_of_measure_sale.name")
 */
class Product {

    private $id;

    /**
     * @ORM\...(targetEntity="unit_of_measure")
     * @GRID\Column(field="unit_of_mesure_buy.name", title="Buy")
     */
    private $unit_of_mesure_buy;
    
    /**
     * @ORM\...(targetEntity="unit_of_measure")
     * @GRID\Column(field="unit_of_mesure_sale.name", title="Sale")
     */
    private $unit_of_mesure_sale;
}
````
The `field` attribute is the name of the related field of the property.
