### ISSUE TITLE
BUG when you set default filters and try to manipulate query

### ISSUE THREAD

**Issue by gribos** [APY/APYDataGridBundle#739]
sample code :

        $grid = $this->get('grid');
        $grid->setDefaultFilters(array(
            'closeDate' => array('operator' => 'isNull')
        ));
        $source->manipulateQuery(
            function ($query) use ($tableAlias, $grid) {
                $fileFilter = $grid->getFilter('files.type.id');
                if ($fileFilter && $fileFilter->getOperator() === 'neq') {
                    $query->orWhere('_files_type.id IS NULL');
                }
            }
        );

I got error in file in vendor/apy/datagrid-bundle/Grid/Grid.php at line 2053 

Notice: Undefined index: from

       if (! isset($sessionFilter['to'])) { 
                    $sessionFilter = $sessionFilter['from']; 
        } 

line 2052 probably should looks like :

       if (! isset($sessionFilter['to']) && isset($sessionFilter['from'])) {

please fix this BUG

**Comment by hmert** [comment]
@gribos If you have time, you can help and propose a PR. Or I'd like to do for you.
