### ISSUE TITLE
Display a unique filter field to all grid columns

### ISSUE THREAD

**Issue by bawae** [APY/APYDataGridBundle#749]
Hello, i want to display a unique filter field for all the columns of my grid and not one field for each one.
i'm stuck and i have no idea how to do this.
thanks.

**Comment by Lyssal** [comment]
Hi,
Maybe you can create a custom column just for filter (visible=false, filterable=true) and use $source->manipulateQuery() like this :

```php
 $source->manipulateQuery(function (QueryBuilder $query)
  {
      if (null !== $this->grid->getFilter('monFiltre'))
      {
          $monFiltre = $this->grid->getFilter('monFiltre')->getValue();

          $query
             ->andWhere(...) // your SQL
          ;
    }
});
```
