### ISSUE TITLE
OneToMany & optimisation

### ISSUE THREAD

**Issue by Lyssal** [APY/APYDataGridBundle#751]
Bonjour,

J'ai un question concernant la limitation du nombre de jointures dans les résultats.

Pour être plus concret, prenons l'exemple d'organismes qui possèdent chacun plusieurs missions.
Dans une cellule de mon tableau, je souhaiterai afficher la liste des missions pour chaque organisme (sans GROUP_CONCAT). Le soucis est qu'à chaque ligne, Doctrine va effectuer une requête spécifique. Comment peut-on contourner ce problème ?

J'ai effectué plusieurs tests dont :
```php
$source->manipulateQuery
(
    function (QueryBuilder $query) use($organismeTableAlias)
    {
        $query
             ->leftJoin($organismeTableAlias.'.missions', 'mission')
             ->addSelect('mission')
            ->groupBy($organismeTableAlias.'.id')
        ;
    }
);
```
Évidemment, il ne me retourne qu'une mission par organisme. Et si j'enlève le groupBy, j'ai des lignes en moins (si le premier organisme a 20 lignes et que j'affiche 20 lignes dans mon tableau, je me retrouve avec une seule ligne).
L'idéal serait peut-être d'avoir une sous-requête pour récupérer uniquement les ID que l'on veut et où se feraient les filtres et le groupBy maos je ne pense pas que cela soit possible avec ApyDataGrid.

Y'a-t-il une solution à ce problème ?

Merci d'avance !

**Comment by hmert** [comment]
Hi @Lyssal :) could you explain this in English, please?

**Comment by qferr** [comment]
@Lyssal Can you post your entity ? Thank you
