### ISSUE TITLE
Translation domain

### ISSUE THREAD

**Issue by clubdesarrolladores** [APY/APYDataGridBundle#752]
There is translations domains like grid.es.yml?

**Comment by hmert** [comment]
could you explain it for me? I didn't understand

**Comment by giovkanata** [comment]
Maybe he is referring to the possibility to add a translation domain for the properties of an entity related to a grid. For example when you add a translation key for a title like:
```
/**
  * @var \DateTime
  *
  * @ORM\Column(type="date", nullable=true)
  * @GRID\Column(title="user.birth_date", filterable=false)
  */
   protected $birthDate;
```
you are forced to put the translation only in message.yml and would be nice if we could customize it.

**Comment by clubdesarrolladores** [comment]
Exactly, is a good practice for bundles keep separated domain translations files. But to do this, we need rewrite a lot of templates. I propose this for the next milestone.

**Comment by qferr** [comment]
@APY/collaborators We could add a `translation_domain` property to options of the column.

**Comment by hmert** [comment]
:+1:

**Comment by qferr** [comment]
Causes: 329

**Comment by qferr** [comment]
Done. See the [documentation](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/columns_configuration/annotations/column_annotation_property.md).
