### ISSUE TITLE
Filtering on a Joined Column

### ISSUE THREAD

**Issue by scottshipman** [APY/APYDataGridBundle#753]
I have a Join column defined using annotations that basically joins first name, last name and email address, to display in a single column in the grid. 

```
@GRID\Column(id="salesAgent_full", type="join", columns = {"quoteReference.salesAgent.firstName", "quoteReference.salesAgent.lastName", "quoteReference.salesAgent.email"}, title="Primary Business Admin", export=true, filterable=true, operatorsVisible=false)
```
I also need to filter on this value. However, the filter only works if I enter a value that exists in either of the individual fields that are joined, but not a string value that spans one or more fields. For example, I can type a valid firstName and the filter works as expected, but if I enter a first name and part of last name, it returns zero results.

How do I enable the filter to work on the combined fields value rather than each individually?

**Comment by aftabnaveed** [comment]
@scottshipman  is quoteReference the same entity?

**Comment by scottshipman** [comment]
@aftabnaveed 
the Grid source is based on a parent entity which has a field (quoteReference) to a different entity, which then references a User entity called salesAgent. So, it is nested references. The data in question is the User fields as they exist in the join column. The join works great, but the filter seems to filter the actual fields, not the Joined instance (as if the Join isnt part of an object, just a runtime manipulation)
