### ISSUE TITLE
How to render cell with html?

### ISSUE THREAD

**Issue by umahanov** [APY/APYDataGridBundle#757]
$grid->getColumn('title')->manipulateRenderCell(
            function ($value, $row, $router) use($officeId) {
                return $router->generate('pegas_regnews_edit',array('regional_office_id' => $officeId, 'id' => $row->getField('id')));
            }
        );

This callback renders url, but I need wrapped link:
<a href="url">title value</a>

How cat I achieve this?

**Comment by Lyssal** [comment]
```php
return '<a href="'.$router->generate(...).'">Coucou</a>';
```
doesn't work ?

If it doesn't work, you have to override template and use the "raw" filter somewhere.

**Comment by umahanov** [comment]
Actually, it does not work, cause it renders html as plain text. At that stage html is already rendered.

**Comment by Lyssal** [comment]
Have you override blocks.html.twig and the grid_column_cell block ?

Like this :
```twig
{% block grid_column_cell %}{%- spaceless %}
{% if column.filterable and column.searchOnClick %}
    {% set sourceValue = sourceValue is defined ? sourceValue : row.field(column.id) %}
    <a href="?{{ grid.hash }}[{{ column.id }}][from]={{ sourceValue | url_encode() }}" class="searchOnClick">{{ value }}</a>
{% else %}
    {{ value|raw }}
{% endif %}
{% endspaceless -%}{% endblock grid_column_cell %}
```

**Comment by umahanov** [comment]
Actually, I made decision not to use this bundle. Complex modifications for small task. Thanks

**Comment by aftabnaveed** [comment]
@umahanov  did you go for any other option?

**Comment by aftabnaveed** [comment]
did you actually try to create your own column type? see this
https://github.com/Abhoryo/APYDataGridBundle/issues/677
