### ISSUE TITLE
How do I combine two columns from same entity? 

### ISSUE THREAD

**Issue by aftabnaveed** [APY/APYDataGridBundle#758]
I would like to combine to columns/fields of the same entity into one column, how do I do that, I found this in a different issue but was not sure where to place this code in my Entity?

```
* @GRID\Column(field="full_name", type="join", columns = {"firstName", "lastName"}, title="Full Name", export=true, filterable=true, operatorsVisible=false)
```

Followed this documentation https://github.com/Abhoryo/APYDataGridBundle/blob/master/Resources/doc/columns_configuration/types/join_column.md but no luck.

**Comment by qferr** [comment]
The `id` attribute is **required**. The property `field` cannot be set because the property `isManualField` is forced to true. 

```
use APY\DataGridBundle\Grid\Mapping as GRID;

/**
 * @GRID\Column(id="full_name", type="join", columns = {"firstName", "lastName"}, title="Full Name", export=true, filterable=true, operatorsVisible=false)
 */
class YourClass
{
}
```

**Comment by qferr** [comment]
@aftabnaveed ping !

**Comment by aftabnaveed** [comment]
@qferr  sorry I abandoned using this module, because I switched my application to a single page. 

Thanks

**Comment by qferr** [comment]
Ok. Thank you for your reactivity.
