### ISSUE TITLE
Is this bundle still mantained?

### ISSUE THREAD

**Issue by matteomoretti** [APY/APYDataGridBundle#760]
Hi,

Is this bundle still mantained? Are there any future plans? 

What does @Abhoryo think about?

**Comment by gribos** [comment]
@matteomoretti  good question. @Abhoryo what about version 3.0 of this bundle ?

**Comment by giovkanata** [comment]
@Abhoryo any news about? Are you ok?

**Comment by clubdesarrolladores** [comment]
@Abhoryo ping

**Comment by giovkanata** [comment]
@Abhoryo @golovanov @touchdesign @Spea @nurikabe @print @Gregory @McLean @centove @lstrojny @Benedikt Wolters @Martin Parsiegla @evan someone knows what's happened to Abhoryo?

**Comment by Spea** [comment]
I don't, sorry

**Comment by dfridrich** [comment]
This bundle is probably death. I recomment to use https://github.com/kitpages/KitpagesDataGridBundle

**Comment by Abhoryo** [comment]
Hi, sorry for the late response.
I am glad to see that there are still people using this api.
I'm not in the symfony sphere anymore so it's hard for me to maintain correctly this project.
Someone ask me if he can maintained this bundle so you should see some updates in a few days or a new fork.
The 3.0 version is still unfinished. I don't plan to publish it.
If other persons want to maintain it too. Send me a mail.

(KitpagesDataBundle seems a little too low-level for a symfony bundle. You need to write every thing every times.)

**Comment by hmert** [comment]
Yes, we will maintain the project as a main collaborator.

Please, do not hesitate to contact to us and pull requests are always welcome here :heart:

**Comment by qferr** [comment]
Yes, I would like to maintain this project if possible ? I work on a 2.3 version.

**Comment by hmert** [comment]
@qferr That's great. You're welcome.

I've seen your PR https://github.com/APY/APYDataGridBundle/pull/782
let's discuss from there?
