### ISSUE TITLE
Custom query/ No entity Big Data

### ISSUE THREAD

**Issue by adrian410** [APY/APYDataGridBundle#762]
Hi guys,

I have big data to display (+20,000 rows), from a text SQL query wich is not related to any entity ( because i get the data from a table wich is always changing, so i can't use it as an entity, i have no choice at my job).

So i use "$source = new Vector($data);". But it last at least 2minutes to load everything.

Is there a way to DataGridBundle to change automatically my text query with LIMIT and OFFSET so i don't have to load the whole data at once ? 

If i change it on myself and pass it to "$source = new Vector($data);", i don't have all the pages in the result.

I can't find anything on the docs.

Thanks for help :)

**Comment by hmert** [comment]
https://github.com/whiteoctober/Pagerfanta will work for you.

**Comment by Knallcharge** [comment]
I'm facing the same problem but can't see how Pagerfanta will help here. Is there a way to tell the grid it has 100k items but only feed it an array of 10 and the information about the page it's currently on?
Slicing an array and couting the original number of items can also be done without Pagerfanta but sending the sliced array to the grid will result in a reduced set of data and no way to paginate.
