### ISSUE TITLE
column annotations: pull data from doctrine mapped (manyToMany) class

### ISSUE THREAD

**Issue by matthbull** [APY/APYDataGridBundle#766]
hiya,

Im trying to (using annotations) configure an entity class to display the values of a related class (array collection).

    class User {
          // ......

          /**
           * @ORM\ManyToMany(targetEntity="School", inversedBy="users", cascade={"all"})
           * @ORM\JoinTable(name="user_school")
           * @GRID\Column(title="Schools", field="school.name", type="text")
           */
          protected $schools;

          // ......
    }

Am I barking up the wrong tree? by trying to access the associated class property as in `school.name`?   What Id like to do is display a list of the name propery's of all objects held in association.

Im trying to avoid having to manipulate the column via the controller if possible.

many thanks in advance.

Matt

**Comment by MlleDelphine** [comment]
Hi ! Have you tried to use `type="array"` instead of `type="text"` ?
