### ISSUE TITLE
No metadata information has been found for (Related with #768)

### ISSUE THREAD

**Issue by mikemirten** [APY/APYDataGridBundle#773]
> @aleperin You must add grid annotations in your Entity class

The docs says:

_The Source annotation for a class allows to configure the grid.
It's **optional** if you have declare Column annotation for your properties._

So it is still a bug. And actually the bug is quite serious. I have an auto-generated entities in my project and the columns/properties definition is a traits which used by an entity classes which contains business logic. It means i cannot define the GRID list by the "Source" annotation, but according to the docs i could do it through the "Column" annotations without the "Source" annotation.

And it is quite wearisome to enlist a long list of properties, so it makes sense to let not to enlist properties in the "Source" as a requirement.

**Comment by qferr** [comment]
@hmert This is not a bug. We must fix the documentation and throw an other message for the missing source annotation. Currently, the message is "No metadata information has been found". We should replace by "The source annotation is required."

**Comment by qferr** [comment]
Documentation is right for the master. We must fixed the documentation for the BC version 2.2.

**Comment by DonCallisto** [comment]
Can this be closed?
