### ISSUE TITLE
Translations to the Grid Content

### ISSUE THREAD

**Issue by mrvelamuri** [APY/APYDataGridBundle#779]
When translation is enabled, then by default the translation is getting applied to the titles in Grid By default. 
But the content is not at all getting translated. I tried to find out a suitable solution for this but not found any answer in the internet. 
I have used this library across my site and now since this translation for content is not working, I have to change this with some other plugin. We tried to tweak it in our code, it worked but I don't wanted to tweak some core library. 
Current Issue, 
![translations](https://cloud.githubusercontent.com/assets/14015297/11539126/7870514a-994b-11e5-9c00-c1ffbe5e80e1.jpg)

In this file, apy/datagrid-bundle/Resources/views/blocks.html.twig, if we change line number 131 as below then it will work, <td class="grid-column-{{ column.renderBlockId }}{% if column.class %} {{ column.class }}{% endif %}{% if column.align != 'left'%} align-{{ column.align }}{% endif %}{% if loop.last %} last-column{% endif %}{% if last_row %} last-row{% endif %}">{{ grid_cell(column, row, grid)|trans|raw }}</td>

Can you please provide a quick solution for this, so that I need not to redo all my work to replace DataGrid with some other grid or custom grid?

--
Thanks, 
Lalith

**Comment by qferr** [comment]
Hello,

You have two solutions.

#### Translatable Behavior

For the data translations, you can use the translatable behavior by [Gedmo](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md).

Don't forget to hint the query :

```
$source->addHint(
    Doctrine\ORM\Query::HINT_CUSTOM_OUTPUT_WALKER,
    'Gedmo\\Translatable\\Query\\TreeWalker\\TranslationWalker'
);
```

#### Manipulate column render cell

You can manipulate the render of the cell with the translator service:

```
$translator = $this->getTranslator();

$column->manipulateRenderCell(function ($value) use ($translator) {
    return $translator->trans($value);
}); 
```

**Warning**: the `$value` must exit in your message catalogs.

**Comment by qferr** [comment]
@mrvelamuri ping

**Comment by qferr** [comment]
@mrvelamuri Please reopen this issue if you have more questions.
