### ISSUE TITLE
grid.mapping.manager service scope

### ISSUE THREAD

**Issue by matthbull** [APY/APYDataGridBundle#780]
with **dev-master**

I know this was mentioned before [here](https://github.com/Abhoryo/APYDataGridBundle/pull/401) (and fixed?) but its still causing a deprecation warning in symfony 2.8

> The "scope" attribute of service "grid.mapping.manager" in file "/var/www/vhosts/project.dev/public_html/vendor/apy/datagrid-bundle/DependencyInjection/../Resources/config/services.xml" is deprecated since version 2.8 and will be removed in 3.0

**Comment by hmert** [comment]
it will be fixed at 2.3,  If you have time, propose a PR. You're welcome here.

**Comment by npotier** [comment]
Closing this issue as the problem seems to be solved. Feel free to reopen it if needed
