### ISSUE TITLE
Release before v2.3

### ISSUE THREAD

**Issue by b-durand** [APY/APYDataGridBundle#784]
@hmert @delirehberi we need a last patch version (v.2.2.17 at e961c1958cc3d9a90cc89eff8d94a390661b74c5) before upgrade to v2.3 with a lot of commit.
(and v2.2.15 at e64995976b99946f0ce032fa7c8b57a34012092b :smile:)

This is not a good pratice to write a commit instead of tag in composer.json.

**Comment by hmert** [comment]
https://github.com/APY/APYDataGridBundle/releases/tag/2.2.17
