### ISSUE TITLE
Missing break statement

### ISSUE THREAD

**Issue by qferr** [APY/APYDataGridBundle#796]
- [Column#631](https://github.com/APY/APYDataGridBundle/blob/master/Grid/Column/Column.php#L631)
- [Source#312](https://github.com/APY/APYDataGridBundle/blob/master/Grid/Source/Source.php#L312)
- [Source#317](https://github.com/APY/APYDataGridBundle/blob/master/Grid/Source/Source.php#L317)

**Comment by b-durand** [comment]
Bad idea for me: I think it is voluntary.

**Comment by qferr** [comment]
@b-durand May be but if it's voluntary, this is a bad practice.

**Comment by b-durand** [comment]
@qferr why (refactor)? The bad pratice is to skip break statement without a comment ([see PSR-2](http://www.php-fig.org/psr/psr-2/#5-2-switch-case)).

**Comment by qferr** [comment]
I agree with you ;)

**Comment by hmert** [comment]
EOF ;)
