### ISSUE TITLE
Grid Column in Extended Entity

### ISSUE THREAD

**Issue by Canser** [APY/APYDataGridBundle#808]
Hello.

Is there anyway to make column definition on my entity that extends another?
One of my columns (title) in the extended entity. When i define source columns like id - title, title is blank.

**Comment by qferr** [comment]
@Canser Have you look [Add column](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/add_column.md) ?

**Comment by qferr** [comment]
Closing as there is no feedback.
