### ISSUE TITLE
Export format dos not work !!

### ISSUE THREAD

**Issue by medooch** [APY/APYDataGridBundle#816]
Hi all,
i use this bundle to manage DataGrid : 
but the exporter dosn't work for me.

Here is my gruid Builder : 

public function setGruid($bundle, $entity, $update, $route){
        $source   = new Entity($bundle.':'.$entity);
        $grid = $this->get('grid');
        $grid->setSource($source);
        // $grid->setRouteUrl($this->generateUrl($route.'_ajax'));
        // OR add a second row action directly to a new action column
        $rowAction1 = new RowAction('Edit', $update);
        $rowAction2 = new RowAction('Delete', $route.'_delete', true);

        $actionsColumn2 = new ActionsColumn('info_column_2', 'Actions', array($rowAction1, $rowAction2));
        $grid->addColumn($actionsColumn2);
        // $deleteAction = new MassAction('Delete', 'MyProject\MyBundle\Controller\DefaultController::deleteAll');
        // $grid->
        $grid->addMassAction(new DeleteMassAction(true));

        $grid->isReadyForRedirect();

        $this->addExporter($grid, $entity);
        $grid->setLimits(array(
                                5 => '5',
                                10 => '10',
                                15 => '15',
                                20 => '20',
                                50 => '50',
                                100 => '100'
                            ));
        $grid->setMaxResults(50);
        $grid->setNoDataMessage(false);
        return $grid;
    }

    public function addExporter($grid, $entity){       
        $grid->addExport(new Exporter\CSVExport('CSV', $entity));
        $grid->addExport(new Exporter\ExcelExport('Excel', $entity));
        $grid->addExport(new Exporter\JSONExport('Json', $entity));
        $grid->addExport(new Exporter\SCSVExport('SCSV', $entity));
        $grid->addExport(new Exporter\TSVExport('TSV', $entity));
        $grid->addExport(new Exporter\XMLExport('Xml', $entity));
    }

This is my views result : 

![capture d ecran 2016-01-24 a 02 24 32](https://cloud.githubusercontent.com/assets/12831762/12533876/b3ef51b6-c241-11e5-936d-f3ca51fdb23e.png)

and this is the error that ive got when i try to export my data : 

![capture d ecran 2016-01-24 a 02 25 59](https://cloud.githubusercontent.com/assets/12831762/12533878/d566ce46-c241-11e5-8ac6-c51bdf8bf742.png)

Any helps please ?

**Comment by qferr** [comment]
Call `$grid->isReadyForRedirect()` after all grid configuration.

```
{
    // ... grid configuration
 
    $grid->isReadyForRedirect();

    return $grid;
}
```
