### ISSUE TITLE
Creating New Column Type / Parameters Always Null.

### ISSUE THREAD

**Issue by Canser** [APY/APYDataGridBundle#817]
Hello.

My problem is when i try to add a column (my custom column or blank does not matter), parameters always empty in the constructor or initializer.

Call for column;

        $image_column = new ImageColumn([
            'id' => 'main-image',
            'title' => 'Resim',
            'size' => '150',
            'width' => 150,
            'height' => 150,
            'orderable' => false,
            'filterable' => false
        ]);

        $grid->addColumn($image_column, 2);

Column Class:
    // tried with the __construct method either but did not work...

    public function __initialize(array $params)
    {
        var_dump($params); die; // returns null...

        parent::__initialize($params);

        $this->setFilterable(false);
        $this->setOrder(false);
    }

    public function getType()
    {
        return 'image';
    }

Am i missing something? Thank you!

**Comment by qferr** [comment]
Hi @Canser,

Have you extend your class with the `Column` class ?

**Comment by Canser** [comment]
Hi @qferr,

Thanks to @delirehberi i see there is no problem with the codes but my templating...

When i exit program after dumping the data, it always null. Removed die and saw the parameters defined .
