### ISSUE TITLE
Cannot install on Symfony 3.0

### ISSUE THREAD

**Issue by vcpawate** [APY/APYDataGridBundle#818]
Please find the error when  I tried to install using composer,

**apy/datagrid-bundle dev-master requires symfony/symfony 2.* -> no matching package found.**

**Comment by qferr** [comment]
Hi @vcpawate,

Symfony 3.0 is not supported. Use Symfony 2.x

**Comment by vcpawate** [comment]
Thanks,  are you planning to support symfony 3?

**Comment by qferr** [comment]
I think that we will mostly rewrite whole project at `3.x` which works on Symfony 3.

**Comment by olix21** [comment]
It could be great to make a symfony 3 compatibility :D

**Comment by metown** [comment]
it could be great to make a symfony 3 compatibility
