### ISSUE TITLE
Manipulating the query builder

### ISSUE THREAD

**Issue by vcpawate** [APY/APYDataGridBundle#825]
I am trying to query database and display results to the APYDataGridBundle, To accomplish this I am using your sample example    https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/manipulate_query.md

After trying for some time,I cannot display queried results to that grid, Please find the code below,

`        $source = new Entity('AppBundle:Entity');
        $grid = $this->get('grid');
		
        $conn = $this->get('database_connection');
        $qb = $conn->createQueryBuilder();
        
        $qb->select('id');
        $qb->from('Entity');
        
		$q = $qb->getSql();
        $stmt = $conn->executeQuery($q);
        $items_ids = $stmt->fetchAll( );

        $source->manipulateQuery($qb);
        $grid->setSource($source);
        
        return $grid->getGridResponse('default/grid.html.twig');`

**Comment by qferr** [comment]
Use `$source->setData($items_id);` . The method `manipulateQuery` is useful for manipulating the query that will be used to fetch data.

**Comment by vcpawate** [comment]
thank you so much for reply,

Can you please provide me simple example on how to display data from database to your grid?
I would really appreciate your help

**Comment by vcpawate** [comment]
Also in your comments, can you please tell me from where to get $items_id

**Comment by qferr** [comment]
You're welcome.

```php
<?php
...
public function createUserGrid()
{
    // Get all users
    $users = $this->getDoctrine()
                  ->getManager()
                  ->getRepository('UserBundle:User')
                  ->findAll();

    if (!$users) {
        throw new NotFoundHttpException('No users');
    }

    // Instanciate the grid
    $grid = $this->get('grid');

    $source = new Entity('UserBundle:User');
    $source->setData($users);
	
    // Define the source of the grid
    $grid->setSource($source);

    return $grid->getGridResponse();
}
...
```

**Comment by vcpawate** [comment]
thanks you so much for your support, but I need to display data from the query response received from database,  please help me with that as i am struggling from past 10 days

**Comment by qferr** [comment]
Could you post a code example please ? What is the type of the response data ? My example don't work ?

**Comment by vcpawate** [comment]
i will post code in 10 mins.... and explain the issue

**Comment by qferr** [comment]
Ok. So if you want display only color you can use the method [manipulateQuery](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/manipulate_query.md). Be careful, if you have a custom query builder (qb) you must initialize the source with your qb: 

`$source-> initQueryBuilder($yourQueryBuilder);`

**Comment by vcpawate** [comment]
Can you please post me example... I am beginner ....

**Comment by qferr** [comment]
```php
public function createCarGrid(Request $request)
{
    // Get factory
    $gridFactory = $this->container->get('apy_grid.factory');

    // Creates a source
    $source = new Entity('MyProjectBundle:Car');

    // Creates a grid builder
    $gridBuilder = $gridFactory->createGridBuilder('grid', $source, []);

    // Creates a color column
    $gridBuilder->add('color', 'string');

    // Builds the grid
    $grid = $gridBuilder->getGrid();

    // Handles filters, sorts, exports, ...
    $grid->handleRequest($request);

    // Renders the grid
    return $this->render('MyProjectBundle:Car:list', ['grid' => $grid]);
}
```

See [Make easier the grid constructor with builder and factory pattern](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid.md)

**Comment by vcpawate** [comment]
thank you so much, But I am getting this error

**Comment by qferr** [comment]
Could you post error please ?

**Comment by vcpawate** [comment]
I have updated code as requried, but I am getting following error

Primary column doesn't exists
500 Internal Server Error - InvalidArgumentException

`public function indexAction(Request $request)
    {
        //
      // Get factory
    $gridFactory = $this->container->get('apy_grid.factory');

    // Creates a source
    $source = new Entity('AppBundle:Entity');

    // Creates a grid builder
    $gridBuilder = $gridFactory->createBuilder('grid', $source, []);

    // Creates a color column
    $gridBuilder->add('name', 'text');

    // Builds the grid
    $grid = $gridBuilder->getGrid();

    // Handles filters, sorts, exports, ...
    $grid->handleRequest($request);

    // Renders the grid
    return $this->render('AppBundle:Entity:list', ['grid' => $grid]);
        //`
}

**Comment by vcpawate** [comment]
modified color to name column

**Comment by qferr** [comment]
Sorry, the primary column is required:

```php
$gridBuilder->add('id', 'numeric', ['primary' => 'true']);
```

**Comment by vcpawate** [comment]
But where do I need to insert query?

**Comment by vcpawate** [comment]
The type of column "numeric" not found

> 500 Internal Server Error - ColumnNotFoundException

**Comment by qferr** [comment]
It's not necessary for display one or more columns. Sorry replace `numeric` with `number`...

**Comment by vcpawate** [comment]
Thanks, make modification

```
Unable to find template "AppBundle:Entity:list".
500 Internal Server Error - InvalidArgumentException
3 linked Exceptions: Twig_Error_Loader » InvalidArgumentException » InvalidArgumentException »
```

**Comment by qferr** [comment]
This is an example. You must use your template.

**Comment by vcpawate** [comment]
I would require query because, I would like list all products which are less than item count 5, hence I would require to make this kind of modification, Hence I need a place where i Can place a query and get the results displayed

**Comment by vcpawate** [comment]
Great, I got the code working finally... Thanks

id	name
1	SAM123
2	TOM123
3      SAMTOM
4      SAMS456

Suppose, I would like display information where name equal to SAMTOM...
How would I do that? Do I add any query?

**Comment by vcpawate** [comment]
Can you please help me out?

**Comment by qferr** [comment]
```php
$source->manipulateQuery(function (QueryBuilder $qb) {
    $qb->andWhere($qb->expr()->eq('name', $qb->expr()->literal("SAMTOM")));
});
```

**Comment by vcpawate** [comment]
```
Catchable Fatal Error: Argument 1 passed to AppBundle\Controller\DefaultController::AppBundle\Controller\{closure}() must be an instance of AppBundle\Controller\QueryBuilder, instance of Doctrine\ORM\QueryBuilder given
500 Internal Server Error - ContextErrorException
```

**Comment by qferr** [comment]
Add `use Doctrine\ORM\QueryBuilder `

**Comment by vcpawate** [comment]
I can see that name column do exists in the database, and I Can query and dump the results but I am not sure why it is saying name does not exist

`[1] Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 60 near 'name = 'SAMTOM'': Error: 'name' is not defined.
    at n/a
        in /home/vcp/symfony/inven3/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63

    at Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 60 near 'name = 'SAMTOM'': Error: 'name' is not defined.', object(QueryException))
        in /home/vcp/symfony/inven3/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 483

    at Doctrine\ORM\Query\Parser->semanticalError(''name' is not defined.', array('value' => 'name', 'type' => '100', 'position' => '60'))
        in /home/vcp/symfony/inven3/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php line 586`

**Comment by qferr** [comment]
```php
$tableAlias = $source->getTableAlias();

$source->manipulateQuery(function (QueryBuilder $qb) use($tableAlias) {
    $qb->andWhere($qb->expr()->eq($tableAlias . '.name', $qb->expr()->literal("SAMTOM")));
});
```

**Comment by qferr** [comment]
@vcpawate It work ? Could you close this issue ?

**Comment by qferr** [comment]
@vcpawate Please reopen this issue whether you have more questions.
