### ISSUE TITLE
500 Internal Server Error - Twig_Error_Runtime

### ISSUE THREAD

**Issue by kadala** [APY/APYDataGridBundle#833]
Hi!

I installed the bundle version 2.2.16  into my project but after install the bundle 

and when I execute: 
   $grid->setSource($source);

   $grid->addExport(new SCSVExport('SCCSV Export'));

I got the following error:
   Invalid escaping strategy "" (valid ones: html, js, url, css, html_attr) in        APYDataGridBundle::blocks.html.twig at line 292.

**Comment by hmert** [comment]
You have another error, I think. I linted the twig with https://github.com/asm89/twig-lint
```
{{ value|escape(column.safe)|raw }}
```
