### ISSUE TITLE
No compatibility with symfony 2.8.* ?

### ISSUE THREAD

**Issue by rokasmi** [APY/APYDataGridBundle#843]
I think requirements for symfony should be  "symfony/symfony": "<2.8.*"
Because 2.8 version has a long term support.
My project is on symfony 2.8.3 and i cannot composer update datagrid bundle, because it no longer support 2.8.* ...

**Comment by goshi** [comment]
We are using 2.8 version in production with Grid bundle. And it is ok. Any problem. Why you have added this limitation?

**Comment by qferr** [comment]
Sorry but the APYDataGridBundle `2.3` will not be compatible with the Symfony `2.8`. The APYDataGridBundle `3.0` will be compatible with Symfony `^2.8`.  See [discussions](https://github.com/APY/APYDataGridBundle/pull/794).
