### ISSUE TITLE
update metadata Exception then setClass Exception

### ISSUE THREAD

**Issue by grekpg** [APY/APYDataGridBundle#845]
Hi i must update Apy for symfony 2,8 so install 2.2.16 
but 2.2.16 throw metdata exception so install 2.2.x-dev
but 2.2.x-dev throw Call to undefined method APY\DataGridBundle\Grid\Column\DateColumn::setClass() 

this method is removed ? is there any alternative for setClass ?i used it many times in my projects. What is a reason to remove this feature ?

**Comment by hmert** [comment]
Hi 2.2.17 is the new tag and you have it
https://github.com/APY/APYDataGridBundle/blob/a9a496144c4182fb21e1de75bd05338b936c160b/Grid/Column/Column.php#L890
