### ISSUE TITLE
Limit DeleteMassAction

### ISSUE THREAD

**Issue by mrluciusfox** [APY/APYDataGridBundle#848]
Hi,
I'm using the grid to show a lot of records and I enable the DeleteMassAction. I want to limit the total of deletes a user can do using the DeleteMassAction to void memory errors. Currently if I have for example 50K rows and the user use the Select All option and then the action Delete, it goes to an memory exhausted error, I would like to show a warning to the user and not to process this kind of massive deletes since I have a remove by csv option in my app.
Thanks!

**Comment by hmert** [comment]
IMHO, it would be 1/100000 at near future there is no plan to develop this future. But i tag `Enhancement` for future
