### ISSUE TITLE
Symfony3 support planned?

### ISSUE THREAD

**Issue by fkrauthan** [APY/APYDataGridBundle#849]
Do you guys plan to upgrade this bundle anytime soon to be Symfony3 compatible?

**Comment by qferr** [comment]
@APY/collaborators We would like to close all issues for the milestone [2.3](https://github.com/APY/APYDataGridBundle/issues/801). Next, we will write a standalone component. It will be used in the new bundle `APYDataGridBundle@3.0` for Symfony 3.

**Comment by clubdesarrolladores** [comment]
In my company we are migrating the projects to sf3.0 and this bundle is our most dependency library. There is a estimated date for the symfony 3.0 support release? (at least a beta release)

**Comment by orfin** [comment]
@qferr @Abhoryo we're also extensively using APYDataGrid and it blocks us from migrating to Symfony 3.0. Are there any plans to make it compatible with the latest Symfony?

**Comment by giovkanata** [comment]
@APY/collaborators Are there some news about the time to wait?

**Comment by hmert** [comment]
@APY/collaborators We have tested this PR #854  @yazbahar we may release a dirty hack version for SF3.x users. Please drop your comment here

**Comment by hmert** [comment]
#877 follow up this PR please
