### ISSUE TITLE
Row Action mapping error

### ISSUE THREAD

**Issue by krzys1u** [APY/APYDataGridBundle#856]
I have rowAction like this:

```
$goToIndentAction = new RowAction('invoice.toIndent','my_route',FALSE,'_blank',array('class'=> 'grid_goto_invoice_action'));
$goToIndentAction->setRouteParameters(array('indent'));
```

I have an entity which has a property named 'indent' and I want to redirect user to my_route using indent field value, 

routing for my_route looks like:

```

my_route:
    path:     /{indent}/flow.html
    defaults: { _controller: myBundle:IndentFlow:index }

```

> An exception has been thrown during the rendering of a template ("Parameter "indent" for route "my_route" must match "[^/]++" ("" given) to generate a corresponding URL.") in MyLayoutBundleBundle::grid.html.twig at line 193.

193 line is:
                `<a class="btn btn-inverse btn-xs" href="{{ url(action.route, column.routeParameters(row, action), false) }}" target="{{ action.target }}"{% if action.confirm %} onclick="return confirm('{{ action.confirmMessage }}')"{% endif %}{% for name, value in action.attributes %} {{ name }}="{% if name!='class' %}{{ value }}{% endif %}" {% endfor %}>{{ action.title|trans }}</a>
`

**Comment by qferr** [comment]
Your parameter (or property 'indent') cannot be empty. You should set a default parameter.

**Comment by krzys1u** [comment]
i added it and still doesn't work, is possible to make something like what I want?

**Comment by DonCallisto** [comment]
@krzys1u this

`$goToIndentAction->setRouteParameters(array('indent'));`

should be

`$goToIndentAction->setRouteParameters(array('indent' => 'aValue'));
