### ISSUE TITLE
Erreur GroupBy yml

### ISSUE THREAD

**Issue by QuentinRillet** [APY/APYDataGridBundle#860]
Bonjour, 

Je viens signaler que le groupBy dans un fichier yaml ne fonctionne pas alors qu'il fonctionne bien en annotation dans l'entity. J'ai cherché un peu mais je ne vois pas ou se situe l'erreur.

En restant à votre disposition.

**Comment by J-Mose** [comment]
Bonjour, 

J'ai rencontré ce problème également, j'ai pu corriger le bug ici 
https://github.com/APY/APYDataGridBundle/blob/2.1.16/Grid/Mapping/Driver/Yaml.php#L96 

En remplacant : 
```php
        foreach($groupBys as $group => $groupBy) {
            $this->groupBy[$class][$group] = $groupBy;
        }
```
par : 
```php
        foreach($groupBys as $groupBy) {
            $this->groupBy[$class][$group][] = $groupBy;
        }
```

Je n'ai pas fait de PR car il semblerait que pilote YML ne soit plus présent sur le trunk

**Comment by QuentinRillet** [comment]
Merci d'avoir consacré du temps à mon problème, malheuresement cela ne change rien dans mon cas. Il ne prend pas compte les valeurs mis dans groupBy.

`Source: 
groupBy: ["id"]`

Je ne vois pas d'ou viens le problème :/

**Comment by J-Mose** [comment]
La modification de ces trois lignes a bien corrigée le problème sur mon projet (avec une syntaxe de configuration similaire), 

La variable $group étant écrasée localement par celle du foreach, on perdait l'information du groupe de la grid, je n'ai pas identifié d'autre soucis sur le group by désolé..

**Comment by QuentinRillet** [comment]
Merci de l'info, je vais continuer de regarder !
