### ISSUE TITLE
Creating a grid from a type

### ISSUE THREAD

**Issue by hpavon** [APY/APYDataGridBundle#861]
Hi, 

I'm new to Symfony and I'm having a hard time making this example work:
[https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid.md#creating-a-grid-from-a-type](url)

First it would be great if you include the _**use**_ clauses in the example, for newbies like me it's not obvious.

Second I don't have GridType in my local project althought I can find it here (not sure if it's a good idea to just download it after I installed APYDataGridBundle via Composer). Any hint of why is it not properly installed? Dependencies maybe? I'm using Symfony 2.8

Also I can't make this other work:
[https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid.md#creating-the-grid-from-the-grid-builder](url)

I get an exception because I'm passing _**createGridBuilder**_ an Entity object, not a Source as expected (just changed the class names to fit my own example):
`Catchable Fatal Error: Argument 1 passed to AppBundle\Controller\EmpresaController::createGridBuilder() must be an instance of AppBundle\Controller\Source, instance of APY\DataGridBundle\Grid\Source\Entity given, called in D:\Hek\Devel\php\prueba2\src\AppBundle\Controller\EmpresaController.php on line 56 and defined`

The createGridBuilder method is just copy/paste:

    /** 
     * @return GridBuilder 
     */ 
    public function createGridBuilder(Source $source = null, array $options = []) 
    { 
        return $this->container->get('apy_grid.factory')->createBuilder('grid', $source, $options); 
    } 

The calling method:

    public function listAction(Request $request)
    {
        // Creates the builder
        $gridBuilder = $this->createGridBuilder(new Entity('AppBundle:Empresa'), [
            'persistence'  => true,
            'route'        => 'product_list',
            'filterable'   => false,
            'sortable'     => false,
            'max_per_page' => 20,
        ]);

        // Creates columns
        $grid = $gridBuilder
            ->add('id', 'numeric', [
                'title'   => '#',
                'primary' => 'true',
            ])
            ->add('name', 'text')
            ->add('created_at', 'datetime', [
                'field' => 'createdAt',
            ])
            ->add('status', 'text')
            ->getGrid();

        // Handles filters, sorts, exports, ...
        $grid->handleRequest($request);

        // Renders the grid
        return $this->render('AppBundle:Empresa:list', ['grid' => $grid]);
    }

The entity (just in case):

    <?php
    // src/AppBundle/Entity/Empresa.php

    namespace AppBundle\Entity;

    use Doctrine\ORM\Mapping as ORM;
    use APY\DataGridBundle\Grid\Mapping as GRID;

    /**
     * @ORM\Entity
     * @ORM\Table(name="empresa")
     * @GRID\Source(columns="id, nombre")
     */
    class Empresa
    {
    	/**
    	 * @ORM\Column(type="integer")
    	 * @ORM\Id
    	 * @ORM\GeneratedValue(strategy="AUTO")
    	 */
    	private $id;

    	/**
    	 * @ORM\Column(type="string", length=100)
    	 */
    	private $nombre;

    	/**
    	 * @ORM\ManyToMany(targetEntity="empresa", mappedBy="clientes")
    	 */
    	private $proveedores;

    	/**
    	 * @ORM\ManyToMany(targetEntity="empresa", inversedBy="proveedores")
    	 * @ORM\JoinTable(name="clientes",
    	 *      joinColumns={@ORM\JoinColumn(name="id_empresa", referencedColumnName="id")},
    	 *      inverseJoinColumns={@ORM\JoinColumn(name="id_cliente", referencedColumnName="id")}
    	 *      )
    	 */
    	private $clientes;

    	public function __construct() {
    		$this->proveedores = new \Doctrine\Common\Collections\ArrayCollection();
    		$this->clientes = new \Doctrine\Common\Collections\ArrayCollection();
    	}
    	
    	/**
    	 * Get id
    	 *
    	 * @return integer
    	 */
    	public function getId()
    	{
    		return $this->id;
    	}

    	/**
    	 * Set nombre
    	 *
    	 * @param string $nombre
    	 *
    	 * @return Empresa
    	 */
    	public function setNombre($nombre)
    	{
    		$this->nombre = $nombre;

    		return $this;
    	}

    	/**
    	 * Get nombre
    	 *
    	 * @return string
    	 */
    	public function getNombre()
    	{
    		return $this->nombre;
    	}

    	/**
    	 * Add proveedor
    	 *
    	 * @param \AppBundle\Entity\empresa $proveedores
    	 *
    	 * @return Empresa
    	 */
    	public function addProveedores(\AppBundle\Entity\empresa $proveedores)
    	{
    		$this->proveedores[] = $proveedores;

    		return $this;
    	}

    	/**
    	 * Remove proveedor
    	 *
    	 * @param \AppBundle\Entity\empresa $proveedores
    	 */
    	public function removeProveedores(\AppBundle\Entity\empresa $proveedores)
    	{
    		$this->proveedores->removeElement($proveedores);
    	}

    	/**
    	 * Get proveedores
    	 *
    	 * @return \Doctrine\Common\Collections\Collection
    	 */
    	public function getProveedores()
    	{
    		return $this->proveedores;
    	}

    	/**
    	 * Add cliente
    	 *
    	 * @param \AppBundle\Entity\empresa $cliente
    	 *
    	 * @return Empresa
    	 */
    	public function addCliente(\AppBundle\Entity\empresa $cliente)
    	{
    		$this->clientes[] = $cliente;

    		return $this;
    	}

    	/**
    	 * Remove cliente
    	 *
    	 * @param \AppBundle\Entity\empresa $cliente
    	 */
    	public function removeCliente(\AppBundle\Entity\empresa $cliente)
    	{
    		$this->clientes->removeElement($cliente);
    	}

    	/**
    	 * Get clientes
    	 *
    	 * @return \Doctrine\Common\Collections\Collection
    	 */
    	public function getClientes()
    	{
    		return $this->clientes;
    	}
    }

(Tested db insertion, wth this entity and works so far).

Thanks in advance,

Héctor

**Comment by dszwcz** [comment]
It seems that you are using version 2.2, and this example relates to the dev-master.
