### ISSUE TITLE
Get rid of query string in RowAction route

### ISSUE THREAD

**Issue by hpavon** [APY/APYDataGridBundle#862]
Hi,

I'm tinkering with your bundle and trying to do some basic stuff with RowAction.
It's taken me forever to realize (not sure I did the right way) how could I change this url with query string:

    whatever/delete?id=123

Into this:

    whatever/delete/123

Anyway my request is, could you please explain it clear in the docs? Maybe it's something trivial but hey, we newbies exist  :wink:

Just in case it helps I did something like this (just figuring out).

_In my grid controller's action:_

    ...
    $rowAction = new RowAction('Delete', 'delete_product/{id}');
    ...

_In my delete controller's action routed like this:_

    /**
     * @Route("/product/delete/{id}", name="delete_product/{id}")
     */
    public function deleteAction(Request $request) {
        ...

(Anything else I tried gave me routing exceptions).

**Comment by qferr** [comment]
I think that the route name `delete_product/{id}` is invalid. Use `delete_product` instead.

**Comment by hpavon** [comment]
I thought it was invalid but actually it gave me an error when I wrote just `delete_product`

**Comment by qferr** [comment]
Could you post the error message or a screenshot ?
