### ISSUE TITLE
Making closure of row action an array

### ISSUE THREAD

**Issue by DonCallisto** [APY/APYDataGridBundle#864]
Take a look to [RowAction](https://github.com/APY/APYDataGridBundle/blob/a9a496144c4182fb21e1de75bd05338b936c160b/Grid/Action/RowAction.php)

    /**
     * Set render callback
     *
     * @param  $callback
     * @return self
     */
    public function manipulateRender($callback)
    {
        $this->callback = $callback;
        return $this;
    }
    /**
     * Render action for row
     *
     * @param \APY\DataGridBundle\Grid\Row $row
     * @return null|RowAction
     */
    public function render($row)
    {
        if (is_callable($this->callback)) {
            return call_user_func($this->callback, $this, $row);
        }
        return $this;
    }

That's not suitable for every user. Image that I'm calling `manipulateRender` function two times: one for a specific action that I'm setting up and one to check all actions created, performing operations. Remember that first call is specific for this action whereas the second is a general - and centralized - one.

What's the result? I will override first call and this will (and already has) result in a debug-headache.

What's about this?

    protected $callbacks = [];  // this should be added instead of $callback property

    /**
     * Set render callback
     *
     * @param  $callback
     * @return self
     */
    public function manipulateRender($callback)
    {
        $this->callbacks[] = $callback;

        return $this;
    }
    /**
     * Render action for row
     *
     * @param \APY\DataGridBundle\Grid\Row $row
     * @return null|RowAction
     */
    public function render($row)
    {
        foreach ($this->callbacks as $callback) {
            if (is_callable($this->callback)) {
                if (null === call_user_func($callback, $this, $row)) {
                    return null;
                }
            }
        }
        
        return $this;
    }

That way we can make a kind of "closure stack". If one of the callbacks fails, we simply don't show the column (from docs: if `null` is returned, that column should be excluded). In every other cases, we simply execute the callbacks in the exact order we added.

This also will not break the compatibility with code written before.

Let me know if you are interested into this feature and I will open a PR.

**Comment by hmert** [comment]
@DonCallisto hi, could you purpose a PR for this?

**Comment by DonCallisto** [comment]
@hmert Yes I will

**Comment by hmert** [comment]
Thank you 👍

**Comment by DonCallisto** [comment]
@hmert let me know if you have any easy pick or something like this ;)

**Comment by hmert** [comment]
@DonCallisto it would be great if you want to be an active contributor :) Most of issues are easy, just have a look :)

**Comment by DonCallisto** [comment]
@hmert I'll take a look in my spare time that - to be honest - in October will be almost near to zero.

**Comment by hmert** [comment]
@DonCallisto Sure, many thanks and have a nice working October :)

**Comment by qferr** [comment]
@DonCallisto Please add some tests for the next new features. Thanks.

**Comment by DonCallisto** [comment]
@qferr In my PR tests were present. Maybe them didn't cover all cases, but they were definitely there.

**Comment by qferr** [comment]
@DonCallisto Indeed, your tests works ! But didn't cover all cases. No problem, I will attempt to fix.

**Comment by DonCallisto** [comment]
@qferr yes, I was only try to send you the message that I'm aware of testing but maybe something was not taken into account.
