### ISSUE TITLE
Can't make it work on Sf3, incorrect versioning

### ISSUE THREAD

**Issue by wojciech-gorski-smt** [APY/APYDataGridBundle#873]
I can't get the bundle to work with Symfony3. I get the following error:

`InvalidArgumentException in XmlUtils.php line 96: [ERROR 1866] Element '{http://symfony.com/schema/dic/services}service', attribute 'scope': The attribute 'scope' is not allowed. (in /var/www/sf/web/ - line 23, column 0)`

I'm assuming it's because the bundle is designed to work with Sf2 only, however, the used versioning lets you use the bundle with Sf versions it won't work with.
`"symfony/symfony": ">=2.0.0"`

Things to do:
1. In the current bundle change `"symfony/symfony": ">=2.0.0"` to `"symfony/symfony": "^2.0.0"`
2. Adjust the bundle so it works with Sf3

**Comment by hmert** [comment]
#849

**Comment by hmert** [comment]
Please follow this PR https://github.com/APY/APYDataGridBundle/pull/854
