### ISSUE TITLE
Update to 2.2.17

### ISSUE THREAD

**Issue by Bomere** [APY/APYDataGridBundle#880]
Hello, 

Datagrid Bundle was updated to 2.2.17 (from 2.2.16) and now all operators are displayed while the settings is correct: 
`operatorsVisible: false`

Do you change something?

Other problem seems to come from the update. When you use a date field, it throw this:

> Object of class DateTime could not be converted to string

Thank you

**Comment by hmert** [comment]
@Bomere do you have this problem at current version?

**Comment by Bomere** [comment]
Hello @hmert ,

Yes, I have.

Did you change something in configuration file between 2.2.16 and 2.2.17 ?

**Comment by hmert** [comment]
Yep, https://github.com/APY/APYDataGridBundle/compare/2.2.16...2.2.17

Could you use `2.3.0` ?

**Comment by Bomere** [comment]
If I understood, you stopped the support of yaml configuration files since the new version (2.2.17)...

Is this true ?

In this case, why you didn't stop the use of yaml in a major update like 2.3 ? 
I'll continue to use the version 2.2.16

Thank you for your help!

**Comment by DonCallisto** [comment]
@bomere I did not checked this yaml support drop, but I agree with you except for one point: a major version is 3.x not 2.3, this is just a minor release and btw should assure BC.

@hmert we should check these kind of things carefully
