### ISSUE TITLE
Can't do anything

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#886]
Hi, i'm using symfony 2.7.18 and i have installed APYDataGrid.
I have some data in my DB and they appear in the grid.

But i can't do anything:
- when i want to display the next page i have No Data Message (i have 5k data in DB and only 5 appear)
- when i want to sort or do a search on my column i have No Data Message
Whatever i do i have the No Data message...

Can someone help me ?

Thanks

**Comment by plfort** [comment]
There may be something wrong with your Source, did you try to execute the query (logged in the profiler) directly on your DB ?

**Comment by quentincurtet** [comment]
On my homepage, the queries are OK.

But when i do something like "id eq 1" in my grid, i have no data message and none queries were played

**Comment by qferr** [comment]
Hello, Could you post the controller ?

**Comment by quentincurtet** [comment]
`<?php

namespace AppBundle\Controller;

use APY\DataGridBundle\Grid\Source\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\BrowserKit\Request;

class ExternalController extends Controller
{
    public function indexAction()
    {
        $source = new Entity('AppBundle:External');

        $grid = $this->get('grid');
        $grid->setSource($source);
        // Set the selector of the number of items per page
        $grid->setLimits(array(5, 10, 15));

        // Set the default page
        $grid->setDefaultPage(1);

        $grid->getGridResponse();

        return $this->render('AppBundle:External:index.html.twig', array('grid' => $grid));
    }
}`

**Comment by plfort** [comment]
https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/getting_started.md#return-the-
grid-to-the-template

**Comment by qferr** [comment]
Try this:

```php
return $grid->getGridResponse('AppBundle:External:index.html.twig');
```

**Comment by quentincurtet** [comment]
Thanks it works, but i can't render it in a template ?

https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/getting_started.md#return-the-grid-to-the-template

**Comment by qferr** [comment]
You must call the method `Grid::isReadyForRedirect()` before to render the template. This method handle filters, sorts, ... .

**Comment by quentincurtet** [comment]
Like this ?
`public function indexAction()
    {
        $source = new Entity('AppBundle:External');

        $grid = $this->get('grid');
        $grid->setSource($source);
        // Set the selector of the number of items per page
        $grid->setLimits(array(5, 10, 15));

        // Set the default page
        $grid->setDefaultPage(1);

        $grid->isReadyForRedirect();

        return $this->render('AppBundle:External:index.html.twig', array('grid' => $grid));
    }`

**Comment by qferr** [comment]
Yes, like the example.

You could use the builder and factory for make easier the grid constructor: https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid.md

**Comment by quentincurtet** [comment]
The example i posted doesn't work, i have a No Data message and when i return to the previous page, i got my grid sorted but not in direct

**Comment by qferr** [comment]
Could you try:

```php
$grid = $this->get('grid');

$grid->setSource($source);
$grid->setLimits(5);
// $grid->setDefaultPage(1);

$grid->isReadyForRedirect();

return $this->render('AppBundle:External:index.html.twig', array('grid' => $grid));

```

**Comment by quentincurtet** [comment]
It doesn't work.
It works with 
`
public function indexAction()
    {
        $source = new Entity('AppBundle:External');

        $grid = $this->get('grid');
        $grid->setSource($source);
        // Set the selector of the number of items per page
        $grid->setLimits(array(5, 10, 15));

        // Set the default page
        $grid->setDefaultPage(1);

        $grid->isReadyForRedirect();

        return $grid->getGridResponse('AppBundle:External:index.html.twig');
    }
`
So my problem is solved :)

Thanks again :)
