### ISSUE TITLE
Define the anntotation @GRID in PHP dynamically

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#888]
Hi,

In my project, i need to handle the preferences of the users for the filters.
For example Sally wants the grid with some columns and Pathy with some others.

I want to define @GRID\Source(columns="my columns") for each user.

Is it possible to define it ? I found nothing in the documentation.

**Comment by giovkanata** [comment]
If I well understand your question, you can pass to the grid the preferred column/s (you could store the preferred columns of each user in a DB table). Take a look at how to [Show and hide columns](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/hide_show_columns.md)
