### ISSUE TITLE
Use Model instead of entity

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#889]
Hi,

I wanted to know if it's possible to use Models instead of entity to diplay the datagrid ?

Thanks.

**Comment by giovkanata** [comment]
You should use [Vector source](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/source/vector_source.md) when you don't want to use Entities.

**Comment by quentincurtet** [comment]
Thanks it works :)
