### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#890]
Hi,
For a project, i have some problems and some questions : 
1. Does the ajax work fine in the latest release ? Because i have some problems with this and all the pseudo fixes that were created ?
2. Is it possible to add some link in the column ? For example i want a link on the id to show my user.
3. Is it possible to add a calendar pictogram for the sort on date ?
4. Is it possible to deactivate the field of research in the global filter but to leave it in the column filter?

Thanks

**Comment by quentincurtet** [comment]
Up ?

**Comment by DonCallisto** [comment]
Hi.
I don't really know how to answer to this questions as I'm pretty new to the project.

Having said that, what do you mean with 

> Does the ajax work fine [...] ?

**Comment by quentincurtet** [comment]
In fact the JS works now, but i have 2 grids in one page and when i make a request on one of them, it is duplicated...

**Comment by quentincurtet** [comment]
It works now, i solved my problem, it's specific to my context.

**Comment by quentincurtet** [comment]
But i still need answers to my others questions ^^
