### ISSUE TITLE
limit = 0, division by 0 exception

### ISSUE THREAD

**Issue by fyrye** [APY/APYDataGridBundle#895]
Version: 2.2.17
OS: Windows 10 x64 Pro
symfony/symfony: 2,8.14
php: 5.6.24

**config.yml**
```
apy_data_grid:
    limits:
        20: 20
        50: 50
        100: 100
        0: All
```

**mygrid.html.twig**
```
{{ grid(grid, 'APYDataGridBundle::blocks.html.twig') }}
```

**Steps**
Load a Grid with any number of rows
Change limit to `All` items per page

**Result**

> An exception has been thrown during the rendering of a template ("Warning: Division by zero") in APYDataGridBundle::blocks.html.twig at line 165.

**Expected**

DataGrid to load with no limit and display a page count of 1.

**Suggested Fix**

in /apy/datagrid-bundle/Grid/Grid.php at line 1622

    public function getPageCount()
    {
        return ceil($this->getTotalCount() / $this->getLimit() ?: 1);
    }

**Outcome**
Returns `1` when `$this->getLimit()` returns `0`, otherwise will function normally.

**Comment by DonCallisto** [comment]
Change

apy_data_grid:
    limits:
        20: 20
        50: 50
        100: 100
        0: All

to

apy_data_grid:
    limits:
        20: 20
        50: 50
        100: 100
        1: All

and you're done

**Comment by fyrye** [comment]
@DonCallisto  That would set `setMaxResults(1)` instead of 0. 
Thereby showing only 1 entry per page instead of all entries on a single page.

```php
 private function setLimit()
    {
        if (isset($this->requestParams['start']) && -1 != $this->requestParams['length']) {
            $this->qb->setFirstResult($this->requestParams['start'])->setMaxResults($this->requestParams['length']);
        }

        return $this;
    }
```
