### ISSUE TITLE
Coding standards

### ISSUE THREAD

**Issue by DonCallisto** [APY/APYDataGridBundle#897]
Hi guys,
as I have a fork of this bundle and I'm trying to reintegrate all together, first step I'm taking is to fix all coding standards to state of art (like `array() --> []`, docbloks, and so on).

I'm doing it into my fork while merging master: are you interested in a pull request for this?

Moreover I'm going to fix all twig deprecations that will be there after upgrading symfony to 3.2 version: same question, are you interested in this?

Let me know.

**Comment by hmert** [comment]
@DonCallisto you're very welcome to purpose a pull request for this.

We have already a branch for this. Would you want to continue from this branch.  https://github.com/APY/APYDataGridBundle/pull/877
and tests are also have been deprecated, should be fixed..

Are you in? 😅

**Comment by DonCallisto** [comment]
@hmert well, I've already started from master and been working on it for a couple of days, so maybe for the moment is better to follow this strategy. For tests, let's look at them in a second moment if it's not a big deal :)

**Comment by DonCallisto** [comment]
You can always rebase existing branch if the matter is about twig deprecations ;)
While CS are not a matter of any Symfony version imho. Don't you agree?

**Comment by hmert** [comment]
of course, CS is not matter for SF version. 👍

**Comment by DonCallisto** [comment]
Here you are

https://github.com/APY/APYDataGridBundle/pull/899
https://github.com/APY/APYDataGridBundle/pull/898

**Comment by hmert** [comment]
👏  great!

**Comment by DonCallisto** [comment]
@hmert talking about https://github.com/APY/APYDataGridBundle/pull/898 we should aware future contributors to run cs-fixer or you should do this **before** integrating PR(s).

Command is `./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix`

This will apply all rules listed in config file (that I've submitted as a `.dist`)
