### ISSUE TITLE
Symfony 3 Test

### ISSUE THREAD

**Issue by hmert** [APY/APYDataGridBundle#905]
Hi watchers 💎,

We have a branch with https://github.com/APY/APYDataGridBundle/tree/symfony3 and #877 

Could you test it on your projects, please? 🙃  if it is ok 👍  if not please open an issue.

**Comment by DonCallisto** [comment]
As I said before, I have a fork of this and I can't use directly the bundle because I still have not a bridge between the bundle and my project, so sadly I have business logic of my domain mixed into my fork.
If no one can try, however, we should build a demo for this purpose.

**Comment by hmert** [comment]
@DonCallisto We may create a sample application at https://github.com/APY/APYDataGridBundle-demo-application but our application uses almost every side of APY's and it is running very well https://travis-ci.org/ojs/ojs/builds/184614260

**Comment by DonCallisto** [comment]
Well if in your application you have a good test suite, no need for other checks I suppose.
What we need to do, however, is to build a strong test suite for this bundle: this should be done asap after new version release as tests here are too few.

**Comment by DonCallisto** [comment]
@hmert can we close this?
