### ISSUE TITLE
Display Mapped Columns

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#907]
Hi,

I have many to one relation in my entity but it's a Vector.
When i want to add my mapped column, it's not displayed

```
$analyticColumn = new Grid\Column\NumberColumn([
  'id' => 'analytic_sv',
  'field' => 'analyticSv',
  'title' => 'Analytic',
  'source' => false,
  'filterable' => true,
   'sortable' => true
]);

$source = new Vector($dataGrid);
$this->grid
  ->setSource($source)
  ->hideColumns(['id'])
  ->setDefaultOrder('name', 'asc')
  ->addColumn($analyticColumn)
;
```

**Comment by DonCallisto** [comment]
This sound a little bit strange to me: your code looks good.

**Comment by quentincurtet** [comment]
My source is not an entity but a Vector, can it be the problem ?

**Comment by quentincurtet** [comment]
I haven't put
 /**
 * @GRID\Source(columns="my columns")
 */
because i got an error.
