### ISSUE TITLE
Set Hash for a grid

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#911]
Hi,

I'm using this : https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid.md#creating-the-grid-from-the-grid-builder
In fact, i have a form in which i can choose the columns of my vector to display.
So i need to render the same grid but when i dump it, my hash is null so i wanted to know if it's possible to set a hash to a grid ?

Thanks.

**Comment by DonCallisto** [comment]
Hi @quentincurtet.
Could you reproduce it in a fork so we can check it out and find if it's a bug or it's a misusage?

Thanks

**Comment by quentincurtet** [comment]
Actually i'm working on a private project but i can post my code : 

```
$grids['setting'] = $this->get('route.grid.setting_grid')->getGridActive();
            $form = $this->createForm(
                SettingGridType::class,
                $this->get('route.grid.setting_grid')->getShowedColumns()
            );
            $handler = $this->getSettingGridFormHandler();

            if (true === $handler->handle($form, $request)) {
                $columns = $request->request->get('setting_grid')['columns'];
                $grids['setting']->setVisibleColumns($columns);

                $gridBuilder = $this->createGridBuilder(
                    new Vector($grids['setting']->getSource()->getData()),
                    [
                        'persistence'  => true,
                        'route'        => 'route_setting_index',
                        'filterable'   => true,
                        'sortable'     => true,
                        'max_per_page' => 20,
                    ]
                );

                foreach ($columns as $column) {
                    $gridBuilder
                        ->add(
                            $column,
                            'text',
                            [
                                'title'   => $column,
                                'primary' => 'true',
                            ]
                        );
                }

                $grid = $gridBuilder->getGrid();
                $grid->hash = $grids['setting']->getHash();
                dump($grid);die;
                // Handles filters, sorts, exports, ...
                $grid->handleRequest($request);

                return $this->renderGrid(
                    ['setting' => $grid],
                    $request,
                    'MyBundle:setting:index.html.twig',
                    $form->createView()
                );
            }//end if

            return $this->renderGrid(
                $grids,
                $request,
                'MyBundle:setting:index.html.twig',
                $form->createView()
            );
```
- getGridActive is a personnal method because i can archive data
- getShowedColumns is the list of the column to display
- The for and the handler are here to show the columns wanted by the user

**Comment by DonCallisto** [comment]
Grid hash is automatically computed, why are you doing such thing

    $grid->hash = $grids['setting']->getHash();

?

**Comment by quentincurtet** [comment]
In fact with my form i render he same grid every time, but when i call it in ajax, the hash of the grid changed, like it was not the same grid,so the rendering is not the same...
I need to set the hash ^^

**Comment by quentincurtet** [comment]
Do you have an idea ?

**Comment by DonCallisto** [comment]
This is how `hash` is computed

```
protected function createHash()
{
    $this->hash = 'grid_' . (empty($this->id) ? md5($this->request->get('_controller') . $this->columns->getHash() . $this->source->getHash()) : $this->getId());
}
```

So if you set an `id` to your grid you'll obtain every time the same hash.
ATM I'm not at my PC to investigate how you can pass `id` of the grid but as long as you don't set an id, the hash will change when:

1. controller change (or)
2. columns change (or)
3. source hash change

**Comment by quentincurtet** [comment]
I can't, because the id is not the ajax request

**Comment by DonCallisto** [comment]
I don't understand you or you don't understand me :)
BTW only way to have same has is to:

- construct the grid with the same id
- don't change controller, columns (name, order and so on)
- don't change source

otherwise there's no chance to have same hash

**Comment by DonCallisto** [comment]
Did you resolved this? Can we close the issue?

**Comment by quentincurtet** [comment]
Yeah, i solved it in another way.
Thanks :)
