### ISSUE TITLE
Problem with Twig 2.0

### ISSUE THREAD

**Issue by darius1706** [APY/APYDataGridBundle#913]
Hello, 
we have problem with Datagrid after update to Twig 2.0

Type error: Argument 2 passed to Twig_Template::hasBlock() must be of the type array, none given, called in C:\Users\user\PhpstormProjects\pages\vendor\artscorestudio\datagrid-bundle\Twig\DataGridExtension.php on line 380

**Comment by DonCallisto** [comment]
@darius1706 are you using 3.0 version? If not, I recommend to update.

**Comment by tawfekov** [comment]
pardon me but I've made sure to  install the V3 of  `APYDataGridBundle` , using Symfony `3.3.4` , 
 my code is almost identical to the example and I'm still getting the same error : 

`Type error: Argument 2 passed to Twig_Template::hasBlock() must be of the type array, none given, called in /vendor/artscorestudio/datagrid-bundle/Twig/DataGridExtension.php on line 380`

**Comment by DonCallisto** [comment]
@tawfekov you are on a fork of this bundle as you can see from the error

`/vendor/artscorestudio/datagrid-bundle/`

Please refer to the fork or update to our official bundle.

Thanks.

**Comment by tawfekov** [comment]
oh my bad!  , I've copied it from this page : https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/index.md 
I think it needs to be updated

**Comment by DonCallisto** [comment]
@tawfekov Yes it does. Would you like to open a PR with modification or you prefer me to fix this?

**Comment by tawfekov** [comment]
never mind, I'll do it

**Comment by DonCallisto** [comment]
Ok. Once PR is open, I'll merge it into master.

Thanks.
