### ISSUE TITLE
Problem with showing columns

### ISSUE THREAD

**Issue by quentincurtet** [APY/APYDataGridBundle#917]
Hi,

When i display the grid, i don't use the show and hide columns.
I just want to use the addColumn method.

But my grid display all the columns plus the ones i add...

How can i do to display my grid with the column i add and not all the columns ?

I don't want to use hideColumns.

**Comment by DonCallisto** [comment]
Maybe you can create a grid with a group different from default one, then add all the columns you're interested in.

**Comment by quentincurtet** [comment]
I don't understand what you're saying... ^^

I have a grid with a source (that i can't change), and then i want to set the columns to display dynamically.
But i can't use the method setColumns because it needs an instance of Columns which is not my case (i have TextColumn...).

I do this in order to display the title with a translation.

**Comment by DonCallisto** [comment]
Sorry, your explanation it's not clear to me. Try to bring some example of what you have, what you get and what you would obtain.
Thanks.

**Comment by quentincurtet** [comment]
In the beginning : 
- I have a grid with a source
- I have all my columns that are displayed

I try to redefine the columns to display (because of the translation) by using addColumns dynamically.

In the end : 
- I want my grid to be displayed with the columns that i chose and the title of each column translated.

Is it better ? ^^

**Comment by DonCallisto** [comment]
Show us the code please :)

**Comment by quentincurtet** [comment]
I got a grid service : 
```
public function getGridActive()
    {
        $scsvExport = new SCSVExportModel();
        $scsvExport->setType('SCSVExport');
        $scsvExport->setTitle('common.scsv.export');
        $scsvExport->setFileName('admin.grid.setting.active');

        $this
            ->setOrderColumn('name')
            ->setActionList(
                [
                    [
                        'name' => 'common.edit',
                        'route' => 'admin_setting_edit',
                        'routeParameters' => ['id']
                    ],
                    [
                        'name' => 'common.remove',
                        'route' => 'admin_setting_remove_row_grid',
                        'routeParameters' => ['id']
                    ],
                ]
            )
            ->setColumns(
                [
                    [
                        'type'   => 'TextColumn',
                        'id'     => 'name',
                        'field'  => 'name',
                        'source' => false,
                        'title'  => 'grid.setting.name'
                    ],
                    [
                        'type'   => 'TextColumn',
                        'id'     => 'value',
                        'field'  => 'value',
                        'source' => false,
                        'title'  => 'grid.setting.value'
                    ],
                    [
                        'type'   => 'TextColumn',
                        'id'     => 'description',
                        'field'  => 'description',
                        'source' => false,
                        'title'  => 'grid.setting.description'
                    ],
                ]
            )
            ->setExportParams([$scsvExport])
            ->renderGrid()
        ;

        return $this->grid;
    }//end getGridActive()
```

Then i call the method renderGrid in my abstract service : 
```
public function renderGrid()
    {
        // Setting grid elements.
        $this->grid
            ->setSource(new Vector($this->getDataGrid()))
            ->setDefaultOrder($this->getOrderColumn(), $this->getOrder())
        ;

        // Add columns.
        $this->setColumnsToShow($this->getColumns());

        // Adding export.
        $this->setExport($this->getExportParams());

        // Adding actions.
        $this->renderActionGrid();
    }//end renderGrid()
```

And then i call my method setColumnsToShow with an array in parameter that contain the columns i defined in my grid service : 
```
public function setColumnsToShow(array $columns)
    {
        foreach ($columns as $column) {
            if (true === in_array($column['id'], $this->authorizedColumns)) {
                $columnType = self::COLUMN_PATH.$column['type'];
                $this->grid->addColumn(
                    new $columnType(
                        [
                            'id'     => $column['id'],
                            'field'  => $column['field'],
                            'source' => $column['source'],
                            'title'  => $column['title'],
                        ]
                    )
                );
            }
        }
    }//end setColumnsToShow()
```

**Comment by DonCallisto** [comment]
You're messing things up imho: you should use [manipulateRender](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/manipulate_row_action_rendering.md) for those kind of tasks if I understood your issue correctly.

**Comment by quentincurtet** [comment]
It's only available for rowActions ?

**Comment by DonCallisto** [comment]
@quentincurtet yes, you're right, I've misread and disguise your columns. Well, why don't just call `setTitle` so?

**Comment by quentincurtet** [comment]
Because this method setColumns will also be used to display the columns that the user want ^^

**Comment by DonCallisto** [comment]
Sorry, too abstract for me. One thing I'm pretty sure: centralize that process or approach it like in builder-pattern-style. Hope someone else can help you :)

**Comment by quentincurtet** [comment]
Thanks for your help @DonCallisto i will try to dig harder :)

**Comment by DonCallisto** [comment]
I think your problem is with approach, not with grid comprehension: if you call `add` is up to you to check that column does not exists yet

**Comment by quentincurtet** [comment]
In fact, i could remove all the columns before the render and then i add all my columns

**Comment by DonCallisto** [comment]
It seems and extra effort that you should not do: maybe you can be more "smart" on source/grid creation. Try to rethink your approach. Good luck!

**Comment by quentincurtet** [comment]
Thanks !
