### ISSUE TITLE
Variable name requires "$" in a sample code

### ISSUE THREAD

**Issue by samuelvi** [APY/APYDataGridBundle#924]
The sample from the url:

https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/add_actions_column.md

Needs a "$" for the variable "rowAction2", in the line:

$actionsColumn2 = new ActionsColumn($column, $title, array(rowAction2), $separator);

**Comment by DonCallisto** [comment]
closed https://github.com/APY/APYDataGridBundle/pull/925
