### ISSUE TITLE
Advance in S3 compatibility

### ISSUE THREAD

**Issue by erparom** [APY/APYDataGridBundle#927]
Just a question here:
Any updates for #905 and #877 ? Can I help with something to make Datagrid compatible with Symfony 3? 

Thanks a lot in advance. (If this issue is misplaced or not convenient, please feel free to delete it.

**Comment by DonCallisto** [comment]
To be honest, I don't know why a sf3 compatible version of the bundle is not released yet. 
To me we are ready.

Ping @hmert

**Comment by erparom** [comment]
Thanks @DonCallisto perhaps I should configure composer to use your branch and stop my pain and suffering; cheers and thanks a lot for your help!!!

**Comment by DonCallisto** [comment]
I don' see a tagged version to be honest so it should be released as it seems pretty stable: @hmert use it in other project and I guess it works

**Comment by hmert** [comment]
@erparom sf3 branch is stable and ready to go. At @ojs we're hardly using DataGrid at sf3 branch. 

Let's make it happen :)

**Comment by DonCallisto** [comment]
@hmert could we close this issue? It is more than important to close issues that are not issues or that are done.
