### ISSUE TITLE
The Paginator does not support Queries which only yield ScalarResults.

### ISSUE THREAD

**Issue by lucop1** [APY/APYDataGridBundle#931]
Hi,
I'm using symfony 3.1.10 with APY 3.0.0
When I use this, to get field from another table using Entity as SOURCE:
`@GRID\Column(field="login.username",safe=false,title="Dish Name")`

throw the error:
`The Paginator does not support Queries which only yield ScalarResults.`

I look inside the code and if in the File located in:
/datagrid-bundle/Grid/Source/Entity.php
I replace this:
       
```
        $this->prepareQuery($this->query);
        $hasJoin = $this->checkIfQueryHasFetchJoin($this->query);

        $query = $this->query->getQuery();
        foreach ($this->hints as $hintKey => $hintValue) {
            $query->setHint($hintKey, $hintValue);
        }
        
        $items = new Paginator($query, $hasJoin);

        $repository = $this->manager->getRepository($this->entityName);
```

with this (so revert this piece of to code to 2.3.0)
```
        $this->prepareQuery($this->query);

        $hasJoin = $this->checkIfQueryHasFetchJoin($this->query);
        $query = $this->query->getQuery()
        foreach ($this->hints as $hintKey => $hintValue) {
            $query->setHint($hintKey, $hintValue);
        }
        $items = $query->getResult();
        $repository = $this->manager->getRepository($this->entityName);
```

So replace 
`$items = new Paginator($query, $hasJoin); `
with  
`$items = $query->getResult();`

It works correctly

**Comment by gildasdubois** [comment]
Same error here, and the fix seems ok! Could you integrate it, please?

**Comment by StudioMaX** [comment]
Looks like this issue going from https://github.com/APY/APYDataGridBundle/commit/9449dfb8d123b4d8cfda40942f92ec4cb50ee537
@patgrudniewski, do you remember why this change was needed?

**Comment by StudioMaX** [comment]
Another way to solve this issue is changing
```php
$items = new Paginator($query, $hasJoin);
```
to
```php
$items = new Paginator($query, $hasJoin);
$items->setUseOutputWalkers(false);
```

But I don't understand why we need to use a Paginator here. This `$items` variable used only in one place
```php
foreach ($items as $item) {
```

**Comment by EmericBreal** [comment]
I'm interested by this correction!
