### ISSUE TITLE
question : Can't customize source query columns

### ISSUE THREAD

**Issue by lagaufrette** [APY/APYDataGridBundle#942]
Hello everyone!

I have an issue, and I coudnt find anything in the manual or elsewhere.
A have a big entity with many parameters mapped with a table.

```php
    /**
     * @var string
     * @ORM\Column(name="a", type="string")
     */
    protected $a;

    /**
     * @var string
     * @ORM\Column(name="b", type="string")
     */
    protected $b;

    /**
     * @var string
     * @ORM\Column(name="c", type="string")
     */
    protected $c;

    /**
     * @var string
     * @ORM\Column(name="d", type="string")
     */
    protected $d;
```

and i'm trying to build the query like this : 

```php
class EntRepository extends EntityRepository
{
    public function getCols() {
        $qb = $this->createQueryBuilder('ent')
            ->select(
                'ent.a',
                'ent.c'
            );
        return $qb;
    }
```

And here's my getSource() for the grid : 

```php

    public function getSource()
    {
        // Query builder
        $qb = $this->repository->getCols();

        // Return source
        return parent::getGridSource($qb, ent::class);
    }
```

And at the end, the grid is still displaying all columns, even if they are not in the query.

I know i could hide the columns with PHP but the database query would still have those and it's not efficient enough.

What do you think?
Thanks for reading.

**Comment by DonCallisto** [comment]
Columns are selected automatically from annotations: you can use `groups` of `source` annotation to extract only columns you need.

Take a look at the [docs](https://github.com/APY/APYDataGridBundle/blob/58f4e370ba79bd7d593a3759010ab002b3946b61/Resources/doc/columns_configuration/annotations/source_annotation.md#available-attributes)
