### ISSUE TITLE
Wrong namespace for type Row

### ISSUE THREAD

**Issue by MarekKarmelski** [APY/APYDataGridBundle#943]
File: https://github.com/APY/APYDataGridBundle/blob/master/Grid/Column/Column.php
Line: 181

There is `@param Row $row`, 
but Row is one direcotry higher, 
should be: `@param \APY\DataGridBundle\Grid\Row $row`

**Comment by DonCallisto** [comment]
You're right: would you like to make a PR or should we fix it?

**Comment by MarekKarmelski** [comment]
I will make PR ;)

**Comment by DonCallisto** [comment]
Ok thanks, than refer to this issue in the PR comment so I can close it when merged.

Thanks again for spotting it.

**Comment by DonCallisto** [comment]
Merged https://github.com/APY/APYDataGridBundle/pull/945
