### ISSUE TITLE
Render HTML inside cell

### ISSUE THREAD

**Issue by erparom** [APY/APYDataGridBundle#947]
Hi! First of all I apologize because I saw there are perhaps at least 2 other related issues already created, but I didn't understood solution to be honest. I simply need to render HTML tags as HTML inside a cell. Currently it renders HTML as plain text like:

<p><strong>Se deben cobrar: </strong></p> <p style="padding-left:30px;">-Colegiatur......

And I expected to see the HTML rendered. So perhaps a |raw filter goes in place, but I don't know how to do it. There is no option inside documentation to render HTML so I suppose I need to override a template. Please, if anyone so kind, point me on how to archive this. Thanks a lot in advance

**Comment by erparom** [comment]
For the record, I have some rich text plugins that help me (just as this very block of github issue tracker) to edit a textarea as an html editor. And in some ocassions, I need to render such fields as HTML inside the grid.

**Comment by DonCallisto** [comment]
@erparom take a look at [this](https://github.com/APY/APYDataGridBundle/issues/677)

We should implement an HTMLColumn indeed but, for the moment, you should do it yourself.

Please close the issue if this solve.
Many thanks

**Comment by erparom** [comment]
@DonCallisto Thanks a lot for your help, I'll try to do as you say.
