### ISSUE TITLE
Column from a simple getter

### ISSUE THREAD

**Issue by lmeyer** [APY/APYDataGridBundle#948]
Hello, i have a getter on my Entity that do some calculations.

Can I simply add a grid column with the result of this getter with annotation ? Or do i need to do this with a TextColumn and manipulateRenderCell ?

~~~
public function getSubtotal()
{
    $subtotal = 0;
    foreach($this->getInvoiceLines() as $line) {
        $subtotal += $line->getTotalPrice();
    }
    return $subtotal;
}
~~~

Regards,

**Comment by DonCallisto** [comment]
Hi @lmeyer,
AFAIK you need to perform manual operations you've described above.

**Comment by lmeyer** [comment]
Ok thank you @DonCallisto , 

Can you confirm that the column isn't filterable if i do this ?

**Comment by DonCallisto** [comment]
> Can you confirm that the column isn't filterable if i do this ?

I really don't know but I expect it to be filterable.
