### ISSUE TITLE
Working example with ORMBehaviors Timestampable

### ISSUE THREAD

**Issue by lmeyer** [APY/APYDataGridBundle#949]
Hello,

I use https://github.com/KnpLabs/DoctrineBehaviors for timestampable.

To use the behaviour, i do the following :

~~~
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use APY\DataGridBundle\Grid\Mapping as GRID;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * @ORM\Entity(repositoryClass="AppBundle\Entity\Repository\InvoiceRepository")
 * @ORM\Table(name="invoice")
 * @GRID\Source(columns="id, user.username, state")
 */
class Invoice
{
    use ORMBehaviors\Timestampable\Timestampable;
....
~~~

I don't have a createdAt property in my Entity `use ORMBehaviors\Timestampable\Timestampable` do everything.

I didn't find the way to have a working createdAt grid column with working filters.

Can you tell me if and how is it possible ?

Regards,

**Comment by DonCallisto** [comment]
In our project we use to replicate the column, put annotation on, and everything works.
That's no other way I think to obtain this behavior.

**Comment by lmeyer** [comment]
Is there an example somewhere ?

**Comment by DonCallisto** [comment]
@lmeyer just include that column in your entity and annotate it as you would have done usually.

**Comment by DonCallisto** [comment]
@lmeyer can we close this?

**Comment by lmeyer** [comment]
Yes we can !

I never managed to make the Date columns works with filtering but that's another point.
