### ISSUE TITLE
turn on specified filter?

### ISSUE THREAD

**Issue by Pablossoo** [APY/APYDataGridBundle#954]
How I can turn on specified filter and disable all others?

**Comment by DonCallisto** [comment]
Please, try to explain better what you would to obtain.

Thank you.

**Comment by Pablossoo** [comment]
I would like turn on only e.g equal  filter for all column. I don't need all filters like as greater/smaller etc.

**Comment by DonCallisto** [comment]
Ok, I get it now.

You should call `[setOperators](https://github.com/APY/APYDataGridBundle/blob/master/Grid/Column/Column.php#L682-L687)` on column or you should [construct it directly with proper filters ](https://github.com/APY/APYDataGridBundle/blob/master/Grid/Column/Column.php#L142-L161)

**Comment by Pablossoo** [comment]
Nice, thank you :)

**Comment by DonCallisto** [comment]
You're welcome 😄
