### ISSUE TITLE
DQL function:  CountIf != 0 or >0 or < 0 

### ISSUE THREAD

**Issue by yunaycompany** [APY/APYDataGridBundle#960]
Hi, I am new using amazing bundle ApyDataGrid and I am trying to get in my rows the values greater than 0 or distinct 0. I need help. Thanks

@GRID\Column(field="batchItem.callStatus:countIf:>0", title="Title",defaultOperator="eq",operators={"eq"})
I get this error:
[Syntax Error] line 0, col 203: Error: Expected Doctrine\ORM\Query\Lexer::T_FROM, got ':'

**Comment by DonCallisto** [comment]
Hi.
Remove this from `@Grid` annotation.

What do you use as grid source? An entity? If so you when you init query builder (`$source->initQueryBuilder($qb);`), just provide a query builder that is filtered in a proper way.

I suppose you're using Entity as grid source as you're posting about doctrine error.

Please, let me know and if question is fine, close this.

Thanks.

**Comment by yunaycompany** [comment]
Thanks for answer. I am usign Entity as grid source but i don´t need a filter, with valuesbatchItem.callStatus>0 . I need show this in grid for every row of Entity.My doubt is how can i usign doctrine xtension "countIf" in field of my entity with apydatagrid... Sorry my english. 
Example:
` /**
     * @ORM\OneToMany(targetEntity="Core\Entity\BatchItem", mappedBy="batch")
     * @GRID\Column(field="batchItem.id:count", title="Total",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.callStatus:countIf:0", title="Nunca Procesados",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.callStatus:countIf:1", title="Contactados",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.callStatus:countIf:2", title="Ocupados",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.callStatus:countIf:3", title="Número Erróneo",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.callStatus:countIf:4", title="Contestador",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.schedule:countIf:1", title="Agendas",defaultOperator="eq",operators={"eq"})
     * @GRID\Column(field="batchItem.retries:countIf:0", title="Disponibles para discar",defaultOperator="eq",operators={"eq"})
     */`
This working great but iam need count callStatus if is greater than 0. Ex:
  * @GRID\Column(field="batchItem.callStatus:countIf:**GREATHER:0**", title="Contestador",defaultOperator="eq",operators={"eq"})

**Comment by DonCallisto** [comment]
@yunaycompany so you would like to print a count onto a column? Am I understanding correctly?

**Comment by yunaycompany** [comment]
Yes, @DonCallisto. Thats that i want...

**Comment by DonCallisto** [comment]
Ok, so, remove that annotation, [create *manually* a column](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/add_column.md) than use [manipulate render cell](https://github.com/APY/APYDataGridBundle/blob/master/Resources/doc/grid_configuration/manipulate_column_render_cell.md) where you can get your entity from the `$row` object and perform your calculation.

Hope it's clear.

**Comment by yunaycompany** [comment]
Thanks @DonCallisto . I am resolved my probem with  manipulate render cell.
