### ISSUE TITLE
In-place editing

### ISSUE THREAD

**Issue by talisman-innovations** [APY/APYDataGridBundle#969]
Hi

This bundle looks like exactly what I need - apart from the need to be able to edit the values in the gird in place, in the grid.  So no need to select and edit link etc.  Is this possible in this bundle yet- as I don't see anything in the documentation at the moment.  

Has anybody tried integrating https://vitalets.github.io/x-editable/ for example.

Thanks for your development.

Talisman

**Comment by DonCallisto** [comment]
If I understood correctly, that's not a feature this bundle provide.
ATM I still don't know why bundle maintainer seems to play hide-and-seek, leaving all issues un-answered.
However I don't know if this could be an interesting feature but for the moment I'm gonna close this issue as we have a lot of other work to complete.

Thanks.
