### ISSUE TITLE
[Insight]  Boolean should be compared strictly 

### ISSUE THREAD

**Issue by ousamabenyounes** [APY/APYDataGridBundle#973]
**[in Grid/Source/Source.php, line 460](https://github.com/ousamabenyounes/APYDataGridBundle/blob/20aa2e5904700eeaf8242262ff8cc5df3a2b31f0/Grid/Source/Source.php#L460)**

> With booleans, only strict comparison (with `!==` operator) should be used to lower bug risks and to improve performances.

```php

                $row->setField($fieldName, $fieldValue);
            }

            //call overridden prepareRow or associated closure
            if (($modifiedRow = $this->prepareRow($row)) != null) {
                $rows->addRow($modifiedRow);
            }
        }

        $this->items = $items;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/1e6bf1e6-4dec-4b0a-9856-bf6327804fa4/analyses/3)_

**Comment by DonCallisto** [comment]
Please, open a PR

Thanks.

**Comment by ousamabenyounes** [comment]
I've openned a pull request: https://github.com/APY/APYDataGridBundle/pull/971
