### ISSUE TITLE
Change filter where for on (with)

### ISSUE THREAD

**Issue by clubdesarrolladores** [APY/APYDataGridBundle#975]
I have this dql (example)

`SELECT a FROM entity a LEFT JOIN another b WHERE b.number > 1`

That dql is generated by the datagrid using annotated filters.

But i need change this dql to reach this:

`SELECT a FROM entity a LEFT JOIN another b WITH b.number > 1`

How i can do this?

Thanks.

**Comment by DonCallisto** [comment]
Umh, I don't think that second query is a valid one.

Anyway that's not possibile with this bundle as filters are applied with `WHERE` clause.
