### ISSUE TITLE
Empty datagrid value for a joined column from a related entity

### ISSUE THREAD

**Issue by haroldmodesto** [APY/APYDataGridBundle#979]
My entity (shortened version)

```
@GRID\Source(columns="id, fullName")
@GRID\Column(id="fullName", type="join", title="Full Name", columns={"customers.firstName", "customers.lastName"})
class Parent {
     @ORM\OneToMany(targetEntity="Customers", mappedBy="parent", cascade={"persist"})
     @GRID\Column(field="customers.firstName", title="First Name", type="text", visible=false)
     @GRID\Column(field="customers.lastName", title="Last Name", type="text", visible=false)
    protected $customers;
}
```
Goal is to display the names in one column only. I have tried various combinations and the provided solutions from the issue tracker and other forums but can't get the grid to display values for the Full Name column. It's getting a little frustrating and I kind of think I must be missing something simple.

**Comment by haroldmodesto** [comment]
It works if I include and display the customers.firstName, and customers.lastName too. How can this be done if you only want the fullName column?

**Comment by haroldmodesto** [comment]
Knew it was something simple. This works: 
```

@GRID\Source(columns="id, customers.firstName, customers.lastName, fullName")
@GRID\Column(id="fullName", type="join", title="Full Name", columns={"customers.firstName", "customers.lastName"})
class Parent {
     @ORM\OneToMany(targetEntity="Customers", mappedBy="parent", cascade={"persist"})
     @GRID\Column(field="customers.firstName", title="First Name", type="text", visible=false)
     @GRID\Column(field="customers.lastName", title="Last Name", type="text", visible=false)
    protected $customers;
}
```
Notice that on the source annotation the first and last name are included while being marked visible=false in the propery annotation. My frustration must have gotten me. If this was mentioned in the docs it could have been made more clearer I think.

**Comment by DonCallisto** [comment]
@haroldmodesto 

> If this was mentioned in the docs it could have been made more clearer I think

Do you mind to improve the docs with a PR?

**Comment by haroldmodesto** [comment]
@DonCallisto I'll see if I have time this weekend. Do you have guidelines for submitting PRs?

**Comment by DonCallisto** [comment]
> Do you have guidelines for submitting PRs?

No, actually not.

Feel free to contribute as best as you can, then we'll see together how to improve or integrate your work.

Thanks.
