### ISSUE TITLE
Compatibility with Symfony 4.* ?

### ISSUE THREAD

**Issue by fridde** [APY/APYDataGridBundle#988]
I have started to use Symfony 4.0 for my project and according to Composer, the APYDataGridBundle is not compatible anymore. (```
Your requirements could not be resolved to an installable set of packages.```)

Could someone with more insider knowledge make a quick check of [this list](https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md) and also run the tests against Symfony 4? 

If they pass, the corresponding line in ```composer.json``` could be changed to ```"symfony/symfony": "~2.8|~3.0|~4.0"```

**Comment by DonCallisto** [comment]
This should have been fixed from [3.1.0](https://github.com/APY/APYDataGridBundle/blob/3.1.0/composer.json)

**Comment by linxpatrick** [comment]
I'm trying to install to Symfony 4.1.10. Will not install. Here's what I get. The description of the datagrid looks like it would be useful, if it can be installed.

Using version ^3.1 for apy/datagrid-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.1.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - apy/datagrid-bundle 3.1.0 requires symfony/symfony ~2.8|~3.0|^4.0 -> satisfiable by symfony/symfony[v4.1.0, v4.1.1, v4.1.10, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9].
    - apy/datagrid-bundle 3.1.1 requires symfony/symfony ~2.8|~3.0|^4.0 -> satisfiable by symfony/symfony[v4.1.0, v4.1.1, v4.1.10, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9].
    - apy/datagrid-bundle 3.1.2 requires symfony/symfony ~2.8|~3.0|^4.0 -> satisfiable by symfony/symfony[v4.1.0, v4.1.1, v4.1.10, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9].
    - symfony/symfony v4.1.0 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.1 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.10 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.2 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.3 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.4 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.5 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.6 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.7 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.8 conflicts with __root__[No version set (parsed as 1.0.0)].
    - symfony/symfony v4.1.9 conflicts with __root__[No version set (parsed as 1.0.0)].
    - Installation request for __root__ No version set (parsed as 1.0.0) -> satisfiable by __root__[No version set (parsed as 1.0.0)].
    - Installation request for apy/datagrid-bundle ^3.1 -> satisfiable by apy/datagrid-bundle[3.1.0, 3.1.1, 3.1.2].


Installation failed, reverting ./composer.json to its original content.

**Comment by fridde** [comment]
I might not be the best candidate to comment on this, but to me it looks like a different issue, not related to this (closed) issue.

The "root" package is the name of *your* package (since you haven't specified the parameter ```name``` yet) and somewhere in the dependencies you have stated that you want something very specific. Would you mind linking to a gist of your current ```composer.json``` ?

**Comment by linxpatrick** [comment]
GIT doesn't support json files. Here's the file contents.

{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/apache-pack": "^1.0",
        "symfony/asset": "4.1.*",
        "symfony/console": "4.1.*",
        "symfony/expression-language": "4.1.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.1.*",
        "symfony/framework-bundle": "4.1.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "^1.0",
        "symfony/process": "4.1.*",
        "symfony/security-bundle": "4.1.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.1.*",
        "symfony/twig-bundle": "4.1.*",
        "symfony/validator": "4.1.*",
        "symfony/web-link": "4.1.*",
        "symfony/yaml": "4.1.*"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/dotenv": "4.1.*",
        "symfony/maker-bundle": "^1.9",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.1.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.1.*"
        }
    }
}

**Comment by fridde** [comment]
I don't really understand what you mean by "git doesn't support json files", but anyway:

Why do you have 

    "conflict": {
        "symfony/symfony": ""
     }

in your setup? That might be reason.

**Comment by linxpatrick** [comment]
When I tried to upload the json file, GIT said it didn't support it  
and, in GIT, there's a specific list of what it supports for uploading. 
Maybe I was in the wrong place.

I figured out why the "conflict" line is in the json file. Thanks for 
your suggestion. It broke symfony.

*/Patrick Headley/*
Linx Consulting, Inc.
(303) 916-5522
pheadley@linxco-inc.com
www.linxco-inc.com

**Comment by linxpatrick** [comment]
Removing the "Conflict" line removed many packages from symfony. Restored from a backup. Everything works again except that "composer require apy/datagrid-bundle" still won't install and has the same errors as before.

If I run "composer update" or "composer upgrade" it works. The first time ran "composer update" after the restore, several packages were updated. Now, either command still works but there is nothing to update.

My version comes back as "Symfony 4.1.10 (kernel: src, env: dev, debug: true)". Is it possible that apy/datagrid-bundle has a problem with the version of symfony or one of the other dependencies?
