### ISSUE TITLE
Symfony 3.4 Capability

### ISSUE THREAD

**Issue by aliemre** [APY/APYDataGridBundle#994]
Hi. 

I have started a project as SF 3.4 and I've tried to install APY. So the error came out:

`Your requirements could not be resolved to an installable set of packages.`

After that I tried:

`composer require apy/datagrid-bundle@3.1.0`

`Could not find package apy/datagrid-bundle@3.1.0 at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability`

Unlike 3.4, It perfectly installs APY@3.0 on SF@3.3

How can I manage to install latest release of APY@3.1.0 on SF@3.4

composer.json:
https://gist.github.com/aliemre/50aa952244099e8b1c13dd9f693cc952

**Comment by DonCallisto** [comment]
Could you try to require `3.1.1` version of this bundle?
[This](https://github.com/APY/APYDataGridBundle/releases/tag/3.1.1) should have fixed.

Let me know, thank you.

**Comment by DonCallisto** [comment]
ping @aliemre

**Comment by aliemre** [comment]
Sorry @DonCallisto to reply late. I have tried to install APY on SF 3.1.1. Same error occurred.

![screen shot 2018-03-23 at 14 55 10](https://user-images.githubusercontent.com/761839/37827912-5ede2cec-2eaa-11e8-9bae-4ae66391e345.png)

**Comment by DonCallisto** [comment]
You're still requiring `3.1.0` of this bundle, please try with `3.1.1`

**Comment by kurkowskik** [comment]
I think that 3.1.0 and 3.1.1 need project in stability dev to be installed (because of extra branch-alias in composer.json?)

I cannot test it because my project is based on symfony 4.0.6 which is in conflict with symfony/symfony package required in APY composer.json.

**Comment by aliemre** [comment]
Sorry for misversion. On 3.1.1 still same:

![screen shot 2018-03-26 at 14 32 09](https://user-images.githubusercontent.com/761839/37903947-9126e93c-3102-11e8-840b-dab384be9041.png)

**Comment by kurkowskik** [comment]
Did you tried to change stablity to dev? Add two lines in root (project) composer.json:
```
minimum-stability: dev,
prefer-stable: true,
```

**Comment by aliemre** [comment]
@kurkowskik  Nothing changed. I got the same error unfortunately. I have attached the composer.json and the error screen.

**Composer.json**
https://gist.github.com/aliemre/a04b7540acd13a733daf8c429683b669

** Error:**
![screen shot 2018-03-27 at 18 22 01](https://user-images.githubusercontent.com/761839/37977129-d1784460-31eb-11e8-80c7-d5d95b946e28.png)

**Comment by DonCallisto** [comment]
@aliemre unfortunately... yes.
*BUT* I'm gonna release a new version with some bugfix and without this requirement.
Hopefully in the next hours.

**Comment by DonCallisto** [comment]
I've drafted a new release for this https://github.com/APY/APYDataGridBundle/releases/tag/3.1.2
