### ISSUE TITLE
apy datagrid bundle filter=select is showing error in symfony 3.4. working fine in symfony 2.8

### ISSUE THREAD

**Issue by kannanseeni** [APY/APYDataGridBundle#995]
my code
======
 /**
     * @ORM\ManyToOne(targetEntity="Category")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="CASCADE") 
     * @GRID\Column(title="Category", field="category.category", filter="select", size="50") 
     * @Assert\NotBlank(message="Please select category") 
      */
    protected $category;

Error
=====
Catchable Fatal Error: Argument 1 passed to APY\DataGridBundle\Grid\Source\Source::prepareColumnValues() must be an instance of APY\DataGridBundle\Grid\Column\Column\Column, instance of APY\DataGridBundle\Grid\Column\TextColumn given, called in C:\xampp\htdocs\symfony3.4\radiobooks\vendor\apy\datagrid-bundle\Grid\Source\Entity.php on line 747 and defined

**Comment by DonCallisto** [comment]
What version of the bundle are you using?
Because we have fixed it in [155f69649c230dd3b90ce6fec3f9a38a55094c37](https://github.com/APY/APYDataGridBundle/commit/155f69649c230dd3b90ce6fec3f9a38a55094c37) but we still haven't released a tagged version: maybe we should release a bugfix version

**Comment by DonCallisto** [comment]
I drafted a new release: [3.1.1](https://github.com/APY/APYDataGridBundle/releases/tag/3.1.1), could you try with this and let me know if the issue is gone?

**Comment by kannanseeni** [comment]
It is working fine. thank you very much
